[[abstract]]
== Abstract

The http://www.ogc.org/[OGC] provides a collaborative, consensus process for developing and approving open, international Standards for the geospatial domain. “International Standards”footnote:[As defined in ISO/IEC Directives, Part 2] are those adopted by an international standardizing/Standards organization and made available to the public. Specifically, an OGC Standard is:

A document, established by consensus and approved by the OGC Membership, that provides, for common and repeated use, rules, guidelines or characteristics for activities or their results, aimed at the achievement of the optimum degree of order in a given context.

To guide an open Standards development and approval process, a member approved Policies and Procedures is required.

This document describes the OGC Technical Committee (TC) policies and procedures (P&P). The TC has been granted authority to operate by the OGC Bylaws. The TC is composed of individuals representing organizations that are duly recognized members in good standing of the OGC. The Technical Committee Chair (TCC - see <<role-of-the-technical-committee-chair-tcc>>) facilitates the TC process.

The TC P&P:

* Documents all TC voting processes and procedures;

* Documents the formation, scope and processes required for TC subgroup and committee activities;

* Documents the processes and procedures for submitting, reviewing, and approving a new Standard using the Request for Comment procedures; and

* Documents the process for revisions to adopted OGC^®^ Standards.

As the needs and purpose of the TC change, these policies and procedures changes are approved by an electronic vote of the Voting Members of OGC TC or by recommendation of the OGC Planning Committee (PC). These policies and procedures may be augmented or clarified by Policy Directives issued and approved by the TC or the PC. Such directives are databased and hyperlinked to/from the appropriate portion of this document.

The OGC Technical Committee provides an open, collaborative forum for professional discussion related to the consensus development and/or evaluation, approval, and revision of OGC international Standards. The primary use of approved OGC Standards is to provide the ability to build and deploy interoperable geospatial solutions in the larger Information Technology (IT) domain.

The OGC http://www.ogc.org/ogc/policies/conduct/[Principles of Conduct] govern personal and public interactions in any TC activity.

[[what-is-a-consortium]]
== What is a Consortium?

A broad definition of a consortium is: a combination or group of organizations formed to undertake a common objective that is beyond the resources or capabilities of any single organization. The OGC was formed to provide a collaborative, consensus forum for the discussion and resolution of interoperability issues in the geospatial domain. The work of the consortium is based on volunteerism.

More specifically in the Standards area, a consortium has the following characteristics:

* May or may not have been accredited by any national or global entity;

* Is usually (but not always) international in membership and objectives;

* May have a very narrow or a broad mission (but still generally within a single focus area);

* Has as its primary goal(s) the creation and/or promotion of international Standards (most commonly in the IT area);

* Creates what would be acknowledged to be "open" Standards made available on Reasonable and Non-Discriminatory (https://en.wikipedia.org/wiki/Reasonable_and_non-discriminatory_licensing/[RAND]) terms; and

* May engage in additional activities, such as the creation of white papers, training and certification, but which rarely becomes a "trade association" in the non-tax sense.

The OGC is defined as a Voluntary Consensus Standards Organizationfootnote:[http://www.nist.gov/standardsgov/omba119.cfm[_http://www.nist.gov/standardsgov/omba119.cfm_]].

[[purpose-and-composition-of-the-technical-committee]]
== Purpose and Composition of the Technical Committee

The OGC Corporate bylaws state that the OGC Technical Committee (TC) shall be responsible for developing Standardsfootnote:[OGC Standards are member approved interface and encoding engineering specifications developed via the OGC Consensus process that are publicly and openly available for use in the geospatial and IT community.] through a cooperative consensus process involving the Members. The bylaws provide authority to:

* Design and maintain an http://www.ogc.org/docs/as/[Abstract Specification] for a computing technology independent application environment for interoperable geo-processing and geospatial data products;

* Use the Abstract Specification as a reference to solicit, propose, review, recommend revisions to, and recommend adoption of Standards, also known as OGC Standards;

* Provide the forum for discussing, reviewing, and adopting changes to existing approved OGC Standards;

* Accept, discuss, review, and recommend action on documents developed in the OGC http://www.ogc.org/ogc/programs/ip/[Innovation Program] and then submitted to the TC;

* Discuss, review, and recommend action with regard to Standards and relevant Standards developed in other Standards organizations; and

* Discuss and agree on requirements, use cases, and change requests to existing OGC Standards.

Above all, the TC provides an open forum for professional discussion of issues and items related to the consensus development and/or evaluation and approval of candidate Standards and revisions to existing adopted OGC Standards that provide the ability to build and deploy interoperable geospatial solutions in the larger IT domain. The OGC Principles of Conductfootnote:[http://www.ogc.org/ogc/policies/conduct[_http://www.ogc.org/ogc/policies/conduct_]] govern personal and public interactions in any TC activity.

[[composition-of-the-tc]]
=== Composition of the TC

The OGC Bylaws provide the enabling authority for the OGC TC. The TC has the following composition:

* The Technical Committee Chair (appointed by the OGC President and approved by the OGC Board of Directors (BOD));

* Representatives of all member organizations of the OGC; and

* Other individuals deemed appropriate by the BOD or Planning Committee.


[[role-of-the-technical-committee-chair-tcc]]
=== Role of the Technical Committee Chair (TCC)

The TCC is responsible for facilitating the progress and work of the Technical Committee. The TCC is a post held by appointment of the OGC Chief Executive Officer, to lead the activities of the TC. The TCC is an unbiased member of the TC, and therefore does not vote on Items and Issues except as noted below. The TCC shall ensure the following:

* Note is taken of TC Members, Voting TC Members, and their substitutes and proxies at each meeting;

* Minutes are kept of TC meetings, and distributed by OGC Communication as soon as is practical after the meeting;

* TC meetings are announced with appropriate notice (no less than four months) and that a master schedule is initially published on the OGC website at least 8 weeks prior to each meeting;

* TC meetings are facilitated in general;

* A file of TC meeting minutes and all other distributed materials is kept;

* All electronic mail discussions are kept on file;

* The PC and BOD are kept appraised of the current business of the TC;

* TC resolutions for recommendation to the PC are brought to the attention of the PC;

* The various actions of the TC are issued and processed in a timely, orderly manner; and

* In the event of a tie vote on any given Item or Issue for which a simple majority vote is required, the TCC has the right to cast the deciding vote.

[[clarifications-with-respect-to-the-composition-of-the-tc]]
=== Clarifications with respect to the composition of the TC

Although one or more individuals may represent each member organization of the OGC at TC meetings, only OGC Member organizations with TC voting rights (Strategic, Principal, and Technical Committee Members) can vote on any items or issues related to the adoption of an OGC Standard, approval of membership of the OGC Architecture Board (OAB), the TC Policies and Procedures, or the Standards Baseline. For these votes, only one individual may vote on behalf of each such Member organization. There is no limit to the number of TC members that may represent each OGC member organization at TC meetings. However, the TCC may limit the number of attendees (on a maximum-per-organization basis) for reasons of meeting space or other operational considerations.

The TCC shall have the authority to nominate and recommend non-OGC organizations to the BOD members for consideration as voting members of the TC for appointment by the BOD.

[[structure-of-the-technical-committee]]
== Structure of the Technical Committee

The TC is the primary group where OGC Standards are developed, discussed, approved, and maintained. The TC members are responsible for the development and maintenance of all Standards and related technical documents. The TC membership includes Voting TC Members, non-voting TC Members, and Invited Guests.

The Technical Committee is comprised of three primary subgroups: the OGC Naming Authority, Working Groups (WG), and Subcommittees (SC) to:

* Evaluate and provide guidance on architecture issues;

* Carry out the development of new proposalsfootnote:[Proposals as used here is meant to be a general term to cover Standards, Discussion Papers, Best Practices, and Engineering Reports.];

* Evaluation of proposals; and

* Provide a forum for the discussion and documentation of requirements for interoperability.

WGs will be formed, carry out their work, and when their work is completed, be dissolved. Working Group Policies and Procedures are defined in <<policies-and-procedures-for-subgroups-of-the-tc>>.

[[ogc-naming-authority-ogc-na]]
=== OGC Naming Authority (OGC-NA)

The OGC Naming Authority (OGC-NA) controls the assignment of OGC Names to resources of interest in geographic information infrastructures. In the terminology defined in ISO 19135-1:2015, OGC-NA is the Control Body for the register of OGC Names: this document describes the framework of documents, registers and other resources required for OGC-NA to execute that role. There are separate OGC-NA Policies and Procedures.

[[subcommittee-sc-of-the-tc]]
=== Subcommittee (SC) of the TC

A group (organizationally, a subgroup of the TC) of individuals composed of members of the TC and Invited Guests, with a mission to provide recommendations to the TC in some general area. A http://www.ogc.org/projects/groups/sc/[Subcommittee] does not generate a Standard nor does it work on a Standard.

SCs have Voting TC Member-only voting. As with all OGC groups, each Voting TC Member has only one vote per SC. SCs are long-standing entities with general portfolios or mission. OGC staff can chair TC SCs. Any OGC member can attend a SC meeting and participate.

A SC may be proposed by any TC member. The TCC shall determine whether the SC should be established and whether a charter is necessary.

[[working-groups-wgs]]
=== Working Groups (WGs)

A group (organizationally, a subgroup of the TC) of individuals composed of members of the TC and invited guests, with the specific intent of solving some particular interoperability problem or problems in a particular technology domain for recommendation to the TC. A Group is not a subcommittee as outlined by the Bylaws of the OGC.

There are two types of Working Groups in the TC: http://www.ogc.org/projects/groups/wg/[Domain Working Groups] (DWGs) and http://www.ogc.org/projects/groups/swg/[Standards Working Groups] (SWGs). The reason that there are two different type of Working Groups is due to the OGC Intellectual Property Policy. The OGC IP Policy can be downloaded from http://www.ogc.org/ogc/policies.

[[domain-working-group]]
==== Domain Working Group

A group (organizationally, a subgroup of the TC – <<policies-specific-to-a-domain-working-group>>) of individuals composed of members of the TC and invited guests, with the specific intent of discussing and/or solving some particular problem or problems in a particular domain or technology arena for recommendation to the TC. Key functions of the Domain Working Group (DWG) are to:

* Have a formal approved charter that defines the DWGs Scope of Work and estimated timeline for completion of the work (if applicable);

* Provide a forum for discussion and documentation of interoperability requirements for a given information or user community;

* Provide a forum to discuss and recommend document actions related to Interoperability Program Reports;

* Develop Change Request Proposals (CRPs) for existing OGC Standards;

* Develop Engineering Reports with the intent seeking approval by the TC for release of these documents as OGC White Papers, Discussion Papers or Best Practices Papers;

* Informational presentations and discussions about the market use of adopted OGC Standards;

* Have all-member voting policies (unless otherwise stated); and

* Have missions and goals defined by the TC.

A DWG Does Not work on OGC Consensus Standards process submissions, candidate Standards, or revisions to existing OGC Standards. However, a DWG can develop change requests as document interoperability requirements that can then be submitted as work items to a SWG.

By default, a DWG will allow public collaboration, such as in teleconference, email discussions, or a public twiki. A DWG has the option to make a motion to the TC to remove public participation in the DWG.

[[Standards-working-group-swg]]
==== Standards Working Group (SWG)

A group (organizationally, a subgroup of the TC) of individuals composed of members of the TC and invited guests with the specific intent of working on a candidate Standard prior to approval as an OGC Standard or on making revisions to an existing OGC Standard. Please see <<policies-specific-to-a-Standards-working-group-swg>> for details on the policies and procedures for SWGs. The following is a general overview.

Specific work items for a SWG could be:

* Have a formal approved charter that defines the SWGs Scope of Work and estimated timeline for completion of the work;

* Develop a new candidate Standard in preparation of that document as an OGC Consensus Standards process submission;

* Process a new OGC Consensus Standards process submission once approved by the OAB;

* Consider official Change Request Proposals to an existing OGC Standard and make changes to the Standard as necessary: from this perspective, a SWG does all the work that was formerly performed by a Revision Working Group;

* Approve a candidate Standard for public comment;

* To vote on any changes to a candidate Standard or to an existing OGC Standard; and/or

* Make recommendations to the entire TC once a document is ready for a formal adoption vote.

Voting is limited to those Members who are either 1.) Charter Members of the SWG or 2.) have formally opted into the SWG and have waited the mandatory 30-day waiting period and requested to be voting members.

SWGs are persistent unless the SWG voting members decide otherwise and choose to dissolve the SWG once they have completed their work as described in their charter or choose to end the work.

[[meetings-of-the-technical-committee]]
== Meetings of the Technical Committee

This section describes the Policies and Procedures for meetings of the OGC Technical Committee.

[[meetings-of-the-tc]]
=== Meetings of the TC

Technical Committee meetings shall be conducted under the general guidance of Robert's Rules of Orderfootnote:[http://www.robertsrules.com/ Robert’s Rules of Order, Eleventh Edition, 2011.] (RONR). Meetings shall be facilitated by the TCC or other appointed representative(s) of the OGC. The planning goal is to have four meetings per year. The number of meetings per year can be changed by a vote of the TC and the PC or by direction of the Board of Directors.

TC meeting dates and locations will be announced as far in advance as possible but no less than four months in advance of the meeting. Announcements will be through formal OGC Communication. All recommendations, summary notes, presentations, and so forth shall be posted to the OGC Member Portal.

[[attendance-at-tc-meetings]]
=== Attendance at TC Meetings

Only members of the OGC, Invited Speakers, and Invited Guests are welcome at TC meetings. Any TC member may send another representative of his or her organization as a substitute to a TC meeting (please note <<proxy-for-voting>>). Subgroups may only meet by being formally scheduled by the TCC or designee during the course of regularly scheduled TC meetings (subgroups cannot have alternative meetings that overlap temporally with the TC Meeting without approval of the TCC or PC).

[[policy-for-invited-guests]]
=== Policy for Invited Guests

From time to time, OGC staff or an OGC member may wish to invite one or more individuals from organizations who are not OGC Members to attend an OGC TC meeting. Reasons for invitations may be to provide technical input, speak (see Policy for Invited Speakers below), or meet with OGC members and/or staff on items and issues germane to the work of the OGC.

Invited Guests (representatives of organizations that are not members of the TC) may actively participate in an OGC meeting at the sole discretion of the TCC. That is, in the interests of ensuring the efficient operation of any meeting, the TCC may limit or eliminate the opportunity of any invited guest to participate in discussion at any meeting.

All Invited Guest invitations and registration must be coordinated with the TCC and the OGC staff responsible for meeting logistics. The steps are very similar to those for Invited Speakers.

* OGC staff or the DWG/SWG Chair provides a formal invitation to the individual with a cc to the TCC and the TC meeting support staff.

* The TCC approves the invitation.

* OGC provides the invited guest with a registration code.

* The invited guest must register with the provided guest registration code.

* Invited guests may or may not have to sign a non-disclosure agreement (NDA). For special meetings held in parallel with the OGC TC meetings, such as an OGC Interoperability Day, summits and workshops, or a Standards Coordination meeting, NDAs are not required.

The Invited Guest may or may not have to pay a meeting registration fee. OGC staff will work with the members to determine the fee structure for Invited Guests for any given TC meeting.

[[policy-for-invited-speakers]]
=== Policy for Invited Speakers

From time to time, OGC staff or Members wish to invite an individual from a non-Member organization to speak at an OGC Working Group meeting or Plenary session. Any invited speaker may attend the TC meetings for the day on which they are speaking without having to pay the TC meeting fee. The process is as follows.

* The DWG/SWG Chair provides a formal invitation to the individual with a cc to the TCC and the TC meeting support staff. The formal invitation may be via email.

* The TCC approves the invitation.

* The OGC provides the invited speaker with a speaker registration code.

* The invited speaker must register with the provided speaker registration code.

If the invited speaker wishes to spend more time at the TC meetings beyond the day on which they are speaking, they will need to pay the required TC meeting fee, unless waived. For the day the invited speaker is attending, they are free to partake of any refreshments but will need to pay for their own lunch or any related OGC social event they wish to attend on that day. Finally, the speaker may need to sign the Standard OGC Non-Disclosure Agreement (NDA).

[[agenda-and-schedule-of-a-tc-meeting]]
=== Agenda and Schedule of a TC Meeting

At least eight weeks before a TC meeting, a draft master schedule for that TC meeting will be posted to the public OGC web site. The agenda is managed solely by the TCC or designee and will be modified prior to the meeting as appropriate. The TCC will maintain a master agenda that is available to members and which is generated from the agendas of each WG as they are populated.

The WG Chairs shall provide the TCC or designee meeting date and time requests at least 4 weeks before the actual TC meeting. The earlier the better!

Each WG Chair shall email an agenda to OGC members at least three weeks before the meeting. Due to schedule conflicts, WG Chairs that fail to provide a proposed agenda by three weeks before the meeting may forfeit the right to meet during the course of regularly scheduled TC meeting times. However, the Chairs of a WG that do not provide an agenda can elect to have an ad-hoc meeting during the off-hours (such as a breakfast or after-dinner session).

[[policies-related-to-the-recording-of-an-ogc-meeting]]
=== Policies related to the recording of an OGC Meeting

If there is a GoToMeeting (or similar technology) session assigned for a specific OGC Working Group, TC Plenary, or PC meeting, there is the option to record the session for later use by OGC staff and OGC members. Guidance for such recording is as follows.

* The members attending the meeting need to be notified that the meeting is being recorded. If there are objections, then the meeting shall not be recorded.

* The recording shall remain members-only and shall not be available to the public. The exception is for open meetings in which the public is invited to attend.

* All recordings shall be uploaded to the appropriate meeting folder on the OGC portal.

[[voting-during-and-between-tc-meetings]]
== Voting During and Between TC Meetings

The following policies address voting during and between TC meetings. One of the primary functions of the TC is to vote on a variety of actions, items, and issues. Votes can be for any purpose pertaining to the format and content of the Abstract Specification, Candidate Standards, OGC Standards, Discussion Papers, approval of the slate of nominations for the OGC Architecture Board, Best Practices Documents, Policies and Procedures of the TC, and for other purposes consistent with the purpose of the TC as described in these Policies and Procedures. The TC will make recommendations to the PC concerning adoption of a candidate Standard, changes to a Standard, creation of a Working Group, a Best Practice, or a policy document and these recommendations require further approval by the PC.

[[voting-thresholds]]
=== [lime]#Voting Thresholds#

[lime]#All thresholds for quorum, sufficiency, and voting are calculated to meet or exceed the fraction or number indicated. For example, a quorum of 1/3 of members means that exactly 1/3 or more members are required to meet quorum. 33.2% does not meet quorum, 33.3333 does.#

[[quorum-for-a-tc-meeting]]
=== Quorum for a TC Meeting

The quorum for any meeting of the Technical Committee Members shall be 1/3 of the total Voting membership as comprised by the Strategic, Principal, Technical, and Technical Aggregate Members. If there is quorum, then a simple majority of the Voting TC Members present at a meeting shall constitute a positive vote for all TC Items and Issues. A roll call will be held at the beginning of each Plenary where votes are to occur to ensure a quorum is present.

The only exception for this Quorum rule is for a vote to issue an electronic vote for adoption of a new or revised version of a candidate Standard, creation of a Working Group, a Best Practice, or a policy document. In this case, a simple majority vote of those TC Voting members present constitutes a successful vote.

[[three-week-rule]]
=== Three Week Rule

For votes that require documentation, such as adoption of particular documents as Standards or documents to be released for public comment, one third of the Voting TC members in attendance may invoke the requirement that documentation supporting the vote must be available three weeks prior to the vote. The TC may override the 3-week rule by a 2/3-majority vote of Voting TC members in attendance at a meeting.

The three-week rule clause ensures that Voting TC members have adequate time to read, distribute and gather comments on documents before voting on the document at the following TC meeting.

[[voting-at-tc-meetings]]
=== Voting at TC Meetings

Many votes happen during a face-to-face TC Meeting. Votes can occur in a TC Plenary or in any sub-group meeting. Votes may be related to document actions, recommendations for staff action, formation of new sub-groups, approval of WG charters, and so forth. This section provides guidance on the policies and procedures related to votes at TC meetings.

[[votes-that-can-occur-at-a-tc-dwg-face-to-face-meeting]]
==== Votes that can occur at a TC DWG Face to Face Meeting

Any number of votes can occur at a TC DWG meeting. No prior notice is required to have a vote at a DWG meeting during a TC. Any member representative attending a DWG may vote. However, only one member representative from a member organization may vote in a DWG. Any member representative attending a DWG can frame a motion.

The votes that may occur at a DWG are:

* Move to release an Engineering Report as a Discussion Paper;

* Move to initiate an electronic vote to release an Engineering Report or other OGC document as a Best Practices document;

* Move to elevate a Discussion Paper to a Best Practices document;

* Move to recommend to the TC a change in policy or procedure;

* Move to accept or revise a DWG charter;

* Move to dissolve a DWG; and

* Move to modify the charter of a DWG.

All of these motions of the DWG are recommendations to the full TC.

[[votes-that-can-occur-in-a-tc-plenary]]
==== Votes that can occur in a TC Plenary

Many votes usually occur in the Opening or Closing TC Plenary. The following is a matrix of possible votes and who can vote.

[[Table-1]]
.Vote types and allowed voters
[cols=",",]
|==================================================================================
|Vote Type |Who can Vote
|Approval of a White Paper, Discussion Paper, or Engineering Report|Any member
|Election of TC reps to the PC|Any member
|[lime line-through]#Approval of a DWG Charter#|[lime line-through]#Any member#
|Approval of deprecation or retirement of Discussion Paper or Best Practice|Any member
|Approval to start electronic vote for an OGC Best Practices Document|TC Voting Member
|Approval to start electronic vote for adoption of an OGC Standard|TC Voting Member
|Approval to start electronic vote for a revision of an OGC Standard|TC Voting Member
|Approval to start electronic vote for a new TC P&P or other policy document|TC Voting Member
|Approval to start electronic vote for a new [lime line-through]#SWG# [lime]#WG# or Community Standard work activity|TC Voting Member
|Approval of a new SWG Task|TC Voting Member
|==================================================================================
 +For “Any Member” votes, only one member representative from a given Member Organization may vote.

[[form-of-a-document-motion-in-a-sc-or-wg]]
==== Form of a Document Motion in a SC or WG

All SC or WG document votes, except for Best Practices and Standards adoption votes shall have the following language:

_______________
The <Name of the SC or WG> recommends that the TC approve the release of <OGC Document number and Name> as an OGC <White, Discussion, or Engineering> Document.
_______________

Often the following clause is added:

“Pending any final edits to the document.”

Best Practice and Standards adoption votes shall have the following language:

_______________
The <Name of the SC or WG> recommends that the TC approve an electronic vote to recommend <OGC Document number and Name> as a <OGC Best Practice or Adopted Standard>.
_______________

[[proxy-for-voting]]
==== Proxy for Voting

Not every OGC TC Voting member can attend every TC Closing Plenary. Therefore, the OGC maintains a proxy process. The official TC Voting representative for an organization can assign their proxy to another full-time employee of their organization, to another individual from another TC Member voting organization, or to the TCC.

Proxies can be assigned electronically or in written form. The written proxy form is provided for each meeting and are sent to the Voting members via email as well as being posted to the TC meeting folder for which the proxy will be valid. Assignment of proxy to another full-time employee of the Voting member’s organization may be communicated verbally to the TCC in advance of or at the TC Closing Plenary.

Proxy shall be communicated to the TCC in advance of the TC Closing Plenary. The TCC shall send reminders to the Voting Members prior to the meetings.

Proxies are not transitive: that is, if Member A holds a proxy for Member B and Member B holds a proxy for Member C, Member A can only vote on behalf of Member B and CANNOT further vote on behalf of Member C by “proxy to a proxy.”

[[tc-electronic-voting]]
=== TC Electronic Voting

At any time, the TCC, the TC, or a subgroup of the TC may recommend starting an electronic vote. Initiation of electronic votes may be brought by motion and second at a TC plenary meeting, a WG meeting, or by direct action of the TCC. Please refer to <<Table-1>> for what membership level is allowed to vote for any particular vote. The following rules are for official OGC votes related to:

* Adoption of an OGC Abstract and Implementation Standards;

* Adoption of a revision to an existing OGC Abstract or Implementation Standard;

* Adoption of a OGC Policies and Procedures;

* Approval of an OGC Best Practice;

* Election of representatives to the OGC Architecture Board; and

* Approval of a Standards Working Group Charter or a new Community Standard work activity.

[[duration]]
==== Duration

Unless otherwise stated by the TCC or designee, the normal deadline for response to an electronic vote shall be 45 days from the date of issuance of the electronic vote. There are no extensions for NO votes or insufficient votes (see <<sufficiency>>). The start and end dates for any given vote are set by OGC staff and are posted with the ballot and announced.

[[continuity]]
==== Continuity

Except for the following reasons, an electronic vote shall remain open for the duration as stated in <<duration>>:

* A WG withdraws the motion to approve a candidate Standard (see <<withdrawal>>); or

* The TCC, the OAB, or the WG identifies a procedural error and requests the vote be stopped.

[[eligibility]]
==== Eligibility

All Voting TC Membersfootnote:[The total of Strategic, Principal, Technical, and Technical Aggregate Members] in good standing at any time during the electronic vote can participate in electronic voting, whether or not they have participated in any preceding TC meeting or electronic vote. All such Members are referred to as "Eligible Voters." Each Eligible Voter shall have one vote.

[[number-of-eligible-voters]]
==== Number of Eligible Voters

For each electronic vote, the number of Eligible Voters shall be determined as of the date of the start of the electronic vote. The number of Eligible Voters for a given vote shall be determined by OGC staff and shall be posted with the ballot and announced. This number shall not change for an active vote regardless of whether members gain or lose voting eligibility.

[[allowable-votes]]
==== Allowable Votes

The Voting Member may vote Yes, No, or Abstain. Abstain counts toward Sufficiency. Comments may be provided with any vote. Any Eligible Voter may change their vote during the voting period but not after the vote is closed.

[[sufficiency]]
==== Sufficiency

For all votes on any OGC document or OGC policy, sufficiency requires 1/3 of the Eligible voters to vote. Further, 15% of the total number of Eligible voters must vote YES.

If during the vote there is a new TC Voting Member, that Member may vote but does not change the Sufficiency rule.

[[approval]]
==== Approval
footnote:[NOTE: All approved OGC Technical Committee document or policy recommendations are then presented as a recommendation to the OGC Planning Committee (PC). The PC shall review the recommendation and either approve the recommendation as is, ask the TC for clarification, or in very few instances not approve the recommendation and ask the TC to provide clarifications or more require more work on the document.]

In addition to Sufficiency thresholds, for documents that are official OGC positions, such as a Standard, creation of a new WG, an OGC Best Practice, or an OGC policy, a motion passes (is approved) if the number of YES votes is twice or more the number of NO votes. All other documents pass with a simple majority.

[[comments]]
==== Comments

Any Eligible Voter that votes may submit a written comment. If an Eligible Voter votes NO, then that Voter shall also submit a written comment explaining their reason for voting NO. For a Standard adoption vote, then the SWG shall respond in writing to all comments within 30 days of the completion of the vote. For other votes, then the appropriate TC sub-group shall respond to the comments. The written response to comments shall be in an OGC document and made available to the OGC Membership. If a motion is withdrawn (See <<withdrawal>>) then no response to comments is required.

[[withdrawal]]
==== Withdrawal

A motion may only be withdrawn by the Working Groupfootnote:[Except for votes initiated by the TCC, such as the election of OAB members.] that made the original motion or by the TCC for procedural reasons. The WG shall have a formal documented vote to withdraw a motion. The reasons for withdrawing a motion are not constrained. The WG shall communicate to the TCC the request to withdraw a motion. The TCC shall then communicate the decision to withdraw a motion to the entire Membership.

[[restarting-a-vote]]
==== Restarting a vote

The following procedures shall be followed for those cases in which a revote is required.

* If a WG withdrew a motion and there is no content change to the document, the WG can at any time request the TCC initiate new vote.

* If a WG withdrew a motion and the content of the document is changed, then the WG needs to restart the approval process (in the case of a Standard: OAB review, public comment, vote).

* If the vote was stopped for procedural problem(s), fix the problem(s), and initiate a new vote.

* If failure to approve the motion (See Approval and Sufficiency), then the appropriate OGC group needs to address all comments, revise the document and restart the Standard approval process with an OAB review, public comment, final edits to the document and a new adoption vote.

[[multi-part-documents]]
==== Multi-part Documents

OGC Standards documents are often broken into parts along modular lines. Adoption votes for such multi-part documents must either be sequential and not overlapping in terms of start and stop dates or in parallel with the same start and stop dates for the vote.

If the votes are in parallel and if a part fails, then any part containing a module dependent upon a module in the failed part also fails. If the vote is sequential, any part containing a module dependent upon a module in a previously failed part cannot be voted until the failed part is re-voted and approved or the dependency is removed.

[[visibility]]
==== Visibility

The following rules relate to transparency of the voting process.

* During and after a vote, individual votes and comments are visible to any OGC member during and after the voting period.

* After the vote is complete, the public only sees the vote result and does not see how an Eligible Voter voted or commented.

* The WG can vote to make public the comments and WG responses to the comments - but shall not provide the name of the Voter who made a given comment.

[[assuming-successful-tc-vote-what-next]]
==== Assuming Successful TC vote, what next?

Once the electronic vote completes and assuming a successful TC vote, the following must occur.

* The TCC shall announce the results of the vote.

* If there are any comments, the submission team or SWG shall respond to all comments submitted during the voting period. The responses to the comments shall be documented in an OGC document that is then posted to pending.

* The TCC shall make a recommendation to the Planning Committee requesting approval of the motion from the Technical Committee. The PC shall have two weeks to consider the motion, ask questions, and approve or reject the motion. Approval in the PC is a simple majority of the PC members.

[[subgroups-of-the-tc-electronic-voting]]
=== Subgroups of the TC Electronic Voting

The procedures for holding electronic votes (e-votes) presented in this section apply to any subgroup of the TC that:

* Has an email reflector on the OGC Portal on which all voting members are subscribed; and

* Has a quorum rule on votes, or a rule that requires a notice to the TC at large of the type of vote being contemplated.

In the event that a motion is made either on the email reflector of a subgroup or in some other scheduled meeting of the subgroup (that lacks quorum and thus cannot act directly), then the chair (or presiding officer of the meeting if the elected chair is not present) may call for a Portal vote as a “measures to obtain a quorum” (RONR, 11th Edition, §40, pages 347-348). The procedure will be as follows.

1.  A motion is made and seconded on the subgroup's email reflector or during a meeting (such as a teleconference) that may not have a quorum.footnote:[Even if the meeting where the motion is made has a quorum, and thus could cast a legal vote, the membership may delay the vote for some period to allow for research into issues that may affect their votes. Under RONR, a motion to "Postpone the motion to a certain time" would be appropriate (see RONR, 11th Edition, §14, page 179). The limits on such a motion applies, such as the postponement cannot be beyond the end of the next scheduled meeting, and certain motions cannot be postponed (adjournment for example) and must be voted on in their normal order. RONR allows such procedures in the absence of a quorum under the "measures to obtain a quorum."]

2.  The chair (or the presiding person at the meeting where the motion was made in conjunction with one of the subgroup’s elected chairs) announces that a Portal e-vote will be taken and summarizes the procedure to be used. This summary includes an opening date (usually immediately or within one week after the motion is made) and a closing date at least one full week after the opening, making the vote last at least 8 calendar days (such as a Monday to Monday schedule).

3.  All requirements for previous announcements as delineated in the TC policy and procedures must be met before the email or Portal vote start date. These requirements may include posting of the associated supporting documents in advance of the vote and/or an official notice to the TC of a pending vote within the subgroup.

4.  Votes must be cast before the end of the closing day at midnight in the time zone of the voter (as recorded by the email send protocol). This mail announcing the vote shall include a formal name for the vote in the subject field.

5.  Any valid voting member of the subgroup may visit the Portal page for the e-vote and cast their vote. The member may change their vote at any time. The last vote cast by the member before the closing date and time is his official vote. Portal votes do not stop until their end date is reached or the vote organizer chooses to withdraw the vote.

6.  Only one vote is allowed per OGC Member organization.

7.  Protests on the procedures involving the vote will be addressed to the subgroup chair, with a final appeal to the TCC and the membership of the TC.

8.  If at least a quorum (1/2) of the subgroup votes (YES, NO or ABSTAIN) then the vote is valid. The original motion passes under the same rules as would have been required in an official meeting.

For most votes that require a simple majority at a quorum-valid meeting, the motion passes only if a quorum is obtained, and the number of YES votes is greater than the number of NO votes.

This procedure shall not be used to suspend the rules or to amend any motion made at a quorum-valid meeting of the subgroup.

[[tc-or-subgroups-of-the-tc-email-voting]]
=== TC or Subgroups of the TC Email Voting

The procedures for holding email votes presented in this section apply to any votes that the TC is eligible to hold in a Closing Plenary or any subgroup of the TC that meets the criteria for holding electronic votes as defined in Section 6.6. Note that use of the Portal electronic voting function is preferred over the use of email voting procedures.

Email votes follow the same process as laid out for TC votes in the TC Meeting (see Section 6.4) or for subgroups of the TC electronic voting (see Section 6.6), with the following additional procedures.

1.  The TCC or subgroup chair sends an email to the appropriate reflector notifying the group of the start of an email vote. The message must specify the item(s) on which the group is voting, include relevant background information, provide the deadline for voting, and define the type of vote (“Hand” or “No Objection”).

2.  “Hand” vote: voting members email the reflector (from the email address listed for the corresponding Portal user) with the vote clearly mentioned in the first few lines of the mail, and optionally in the subject line. Allowed votes are YES, NO, or ABSTAIN. The subject line should include the formal name of the subject of the vote used by the chair in the announcement. A member may change their vote by emailing again at any time before the close of the vote. The last vote cast by the member before the closing date and time is that member’s official vote.

3.  “No Objection” vote: an email vote may consist of a request to the group members for any objection to unanimous consent. Voters with no objection to the ballot do not need to email the chair or reply to the vote announcement. Should there be an objection, the vote will be paused and the objection discussed in the reflector or in a meeting. If the objection is addressed to the satisfaction of the objecting party, the vote will continue for the number of days remaining in the vote from the date at which the vote was paused. If the objection is not removed, then the vote will restart as either a “Hand” vote (see 2 above) or a Portal e-vote.

[[policies-and-procedures-for-subgroups-of-the-tc]]
== Policies and Procedures for Subgroups of the TC

This section describes the Policies and Procedures for Sub-groups of the TC. This includes Domain Working Groups (DWGs) and Standards Working Groups (SWGs).

[[membership-in-tc-subgroups]]
=== Membership in TC Subgroups

A subgroup is composed solely of representatives of current OGC members and (potentially) Invited Guests. Each type of group is chartered by simple majority vote of the TC in the course of normal business and ratified by the PC.

The following rules apply to membership in subgroups of the TC.

* Any OGC member organization may send representatives to attend any meeting of the TC or any subgroup of the TC. The exception is for SWGs. In order to attend a meeting of a SWG, the representative must have opted into the SWG in order to participate (<<participating-in-a-swg-opting-in>>).

* Invited guests may actively participate at the sole discretion of the subgroup’s chair. That is, in the interests of ensuring the efficient operation of any meeting, the chair may limit or eliminate the opportunity of any invited guest to participate in discussion at any meeting. Invited guests cannot vote.

[[role-of-subgroup-chairs]]
=== Role of Subgroup Chairs

The chair of a subgroup is responsible for organizing the activities of that subgroup, including:

* Arranging meetings at times and places convenient for the subgroup membership;

* Announcing meeting arrangements to the entire OGC membership, including a preliminary agenda for the meeting, at least 2 weeks in advance of the meeting;

* Encouraging broad participation of the OGC membership;

* Ensuring that minutes of meetings are taken, and made available electronically to the entire OGC membership within two weeks of the meeting: minutes must include:

a.  A list of persons attending the meeting;

b.  A list of motions, seconds, and outcomes; and

c.  A section that details specific actions taken by members of the subgroup;

* Sending electronic reminders to action holder’s one week before the action is due for completion;

* Ensuring the smooth and orderly running of the meeting;

* Reporting on subgroup activities to the parent body, and PC if requested, including presenting subgroup recommendations (if any);

* Keeping the Chair of the parent body apprised of the progress of the subgroup; and

* Recommending schedule and work plan and managing subgroup resources to accomplish the mission of the subgroup.

[[inactive-subgroups]]
=== Inactive Subgroups

The TCC will provide a list to the TC at least once a year of those subgroups that have not met in the previous 12 months. The TC will then vote to determine if these groups should be continued, disbanded or possibly combined with more active groups.footnote:[In the past, some groups have not met for a considerable time and are no longer active. The existence of these groups can be misleading to those trying to understand what OGC is currently doing. This proposal suggests a mechanism for reviewing subgroups and taking some action when appropriate. This will help ensure the groups in OGC are aligned with the actual work being done within the TC.]

[[subgroup-meetings]]
=== Subgroup Meetings

Subgroups except as noted above may set their own meeting schedules. In particular, they do not have to meet every time their parent body meets, nor are they prevented from organizing meetings not co-located with those of the parent body, provided that in every case the relevant meeting notice and reporting criteria are met (see <<meetings-of-the-tc>>).

[[formation-of-a-sub-groupworking-group]]
=== Formation of a Sub-Group/Working Group

At any time, a group of Members may determine that a new area of technology or domain exploration is required. This interest may lead to the formation of a new OGC Working Group. The following are the usual steps related to the formation of a new WG. Typically, the first step is to call an ad-hoc meeting at a face-to-face TC meeting. An ad-hoc meeting is to 1.) judge interest in forming the new sub-group and 2.) define the scope of work for the proposed new sub-group.

[[ad-hoc-meetings]]
==== Ad-hoc Meeting(s)

Any group of OGC members can schedule an ad-hoc meeting. The interested members develop a basic agenda and draft mission statement for the work of the group and call for an ad-hoc meeting at a scheduled TC event or by teleconference/webinar. Like any sub-group, they shall schedule a meeting time and post the meeting time information on the OGC Portal Calendar. Also, like any other sub-group meeting of the TC, they shall announce the meeting to the broader TC and communicate an agenda. At this Ad-hoc meeting, the participants continue to frame the mission and the scope for a proposed new WG or other OGC activity. They must also determine whether there is adequate Member interest to actually form a new WG.

[[development-of-a-proposed-sub-group-charter]]
==== Development of a proposed Sub-Group Charter

The primary function of the Ad-hoc meetings is to write a Charter for the new sub-group/Working Group. The Charter documents the mission, scope, roles, and responsibilities of the proposed WG. Drafts of the Charter can be shared with other members for review and comment. The templates for the Domain and Standards WG Charter documents can be found here:

https://portal.ogc.org/?m=public&subtab=templates&tab=1

[[approval-of-a-sub-group-charter]]
==== Approval of a Sub-Group Charter

Once the Charter is completed and agreed to by the members of the Ad-hocfootnote:[For a Standards Working Group (SWG) charter, the ad-hoc is the submission team.], the following process if followed for approval of the Charter. NOTE: For a SWG Charter, please review <<policies-specific-to-a-Standards-working-group-swg>> for specific requirements related to the formation of a Standards Working Group (SWG).

* The charter is reviewed by the TCC. The TCC shall provide edits and comments in a timely manner.

* The ad-hoc considers the TCC comments and edits the charter as necessary.

* The charter is assigned an OGC document number and posted to pending documents.

* The availability of the draft charter is announced to the TC and to the public and a three-week public review period begins. There is a formal press release with a general call for comments.

* If possible, the draft charter is presented to the TC at a plenary. Otherwise, a PowerPoint or video presentation will be developed and posted to the Portal. NOTE: For a SWG, this presentation should cover the key aspects of the charter, especially the scope of work, the timeline, and the technical discussion related how the Standards work aligns with the current OGC Standards baseline.

* Comments received during the comment period are considered by the ad-hoc members and any necessary changes to the draft charter are completed.

* The modified charter is posted to pending as an update with a new revision number. The TCC shall notify the membership that a revision of the charter has been posted.

[[votes-to-approve-the-charter-and-formation-of-a-sub-group]]
===== Votes to approve the charter and formation of a sub-group

This section describes the voting associated with the approval of specific types of sub-groups: Committees and Working Group. In all cases, the TCC makes the motion to approve the charter for the new sub-group of the TC.

* Committees: Charters for and formation of subcommittees and committees may be approved by a simple majority vote of the membership. These votes happen at the Closing Plenary during a Face-to-Face TC meeting or by email vote per <<tc-or-subgroups-of-the-tc-email-voting>>.

* WG: This is a TC Voting Member vote. Approval of the charter is a simple majority. The TCC initiates a vote to approve the Charter and the formation of the WG. This is an electronic vote under the e-vote rules as stated in <<tc-electronic-voting>>. The TCC shall also send an informational email to the full TC membership asking if there are any final comments or objections to the formation of the new WG.

If the TC approves formation of the new group, then the TC makes a recommendation to the Planning Committee (PC) to approve formation of the new sub-group. These votes may happen at face-to-face meetings or by email votes or by a PC e-vote.

Upon approval of the TC and the PC, the new group will become an official subgroup of the TC.

[[changes-to-a-wg-charter-or-recharter-of-a-wg]]
==== Changes to a WG Charter or Recharter of a WG

The members of a WG may at anytime determine that a change to the WG charter is necessary. Such changes may be done at any time. The WG members need to approve the amended charter by a formally recorded vote. Once the WG members approve the amended charter, the Chair shall inform the TCC who will then assess if the changes are a natural progression of the work of the WG or a major shift in scope of the WG.

* If the TCC judges the changes to reflect a natural progression of the WG work, then the TCC shall notify the full membership of the proposed changes. The amended charter shall be posted to pending documents for a 3-week member review and comment period. The review period is followed by an approval vote by the TC at a Closing Plenary or through an email vote.

* If the TCC judges the changes to reflect a major shift in scope of the WG, then the revised charter shall proceed through the same approval process as a new WG charter in <<approval-of-a-sub-group-charter>>.

* When the recharter vote is requested to start to the TC, the TC has the option to override the TCC vote type recommendation. For instance, if the TCC recommends a vote at the Closing Plenary, the TC can demand instead that a full 45-day electronic vote be held because the TC feels the scope of the revised charter is too different from the original charter.

[[policies-specific-to-a-domain-working-group]]
=== Policies Specific to a Domain Working Group

This section describes the formation, role, and responsibilities of a Domain Working Group (DWG).

[[voting-in-a-dwg]]
==== Voting in a DWG

Voting in DWGs is by simple majority of OGC Members present at the DWG meeting, not just Voting TC Members, with the caveat that no OGC Member organization may cast more than one vote in a WG vote.footnote:[It was felt that WGs should be able to use all of the expertise at hand in arriving at recommendations. All TC member organizations could be represented (and __vote__) at WG meetings in order to allow the expression of all members' opinions. OGC Voting TC Members are protected from control by non-voting members by virtue of the fact that WGs may only form recommendations to the TC and not final TC votes. WG minutes are also available to _all_ members of the TC, so that other TC members may understand and accept or reject WG recommendations.]

[[policies-specific-to-a-Standards-working-group-swg]]
=== Policies Specific to a Standards Working Group (SWG)

A SWG may be formed whenever:

* Three or more members provide a submission for a candidate Standard;

* One or more Change Request Proposals for a given adopted OGC Standard have been submitted to the public Change Request repository on the OGC web site;

* Three or more members wish to define and document a new candidate OGC Standard that will be submitted using the OGC OGC Consensus Standards process; The new candidate Standard could be an interface, encoding, profile, application schema, or extension package; and/or

* Three or more members wish to bring an external document into the OGC process and wish to collaborate to prepare this document for submission using the OGC Consensus Standards process.

The formation and execution of the work of a SWG is closely tied to the OGC Intellectual Property Policies. Members are strongly encouraged to read this Policy prior to forming or joining a SWG.

Whenever a SWG needs to be formed, the first order of business is to inform the TCC The TCC will discuss the process and next steps. The TCC shall announce to the full Membership via OGC communications that there is an intent to start a new SWG (Standards) activity.

The submission team then writes a SWG Charter. Please review the OGC ad-hoc meeting and charter creation and approval process as outlined above in <<approval-of-a-sub-group-charter>>. The policies and procedures defined below are in addition to the requirements to form an OGC Domain WG.

[[the-swg-charter]]
==== The SWG Charter

The Charter documents the scope of work, references, business value, and projected timeline for the new SWG. There is a formal OGC template for a SWG charter. This template may be downloaded from:

https://portal.ogc.org/?m=public&subtab=templates&tab=1

SWG are chartered to create a primary delivery (a new Standard), maintain that Standard, and optionally update, extend, or profile that Standard through a <<swg-task-process>>. At a minimum, the scope of the primary delivery is provided in the SWG charter.

[[ipr-rules-for-a-new-swg]]
===== IPR rules for a new SWG

The charter of each SWG shall also specify whether the SWG to be formed is a RANDfootnote:[Reasonable and non-discriminatory]-Royalty Free SWG or a RAND-for Fee SWG. For a complete discussion of the OGC Intellectual Property Rights (IPR) Policies, please refer to:

https://www.ogc.org/about/ipr

The OGC IPR policy is similar to those of other voluntary Standards organizations.

[[persistent-swgs]]
===== Persistent SWGs

By default, OGC SWGs are persistent until the SWG elects to become inactive or disband. Persistence supports the ability to maintain the Standard products of the SWG, work on multiple revisions of an existing OGC Standard, or to insure that long-term collaboration with other SWGs can be maintained. There may be reasons why a SWG is chartered not to be persistent and such reasons must be described in the charter. The Charter template has a section that specifies whether a SWG is persistent or not.

After a SWG completes its primary delivery, each new proposed SWG deliverable under its in-force charter shall be approved via the <<swg-task-process>>.

[[swg-to-dwg-relationship]]
===== [lime]#SWG to DWG Relationship(s)#

[lime]#During the chartering of a new SWG, a "home" or "parent" DWG must be identified to:#

[lime]#* be a forum for non-IPR-protected discussion of requirements that are relevant to the SWG's work;#

[lime]#* determine when an inactive SWG needs to reactivate to correct or revise a Standard created by the SWG; and#

[lime]#* work with the TCC to address the situation where OGC members are unable or unwilling to reactivate the SWG.#

[lime]#The SWG charter submitters must seek approval from the proposed home DWG for that DWG to function as the home. The DWG may approve this request using the normal DWG voting process. The home DWG must approve the relationship and be identified in the proposed SWG charter prior to the approval of that charter.#

[lime]#In some cases, a SWG is proposed to be formed at the same time as its home DWG is proposed. Under such circumstances, the proposed home DWG is identified in the SWG charter and is effective only if both WGs are approved.#

[lime]#Should either or both the SWG and the DWG wish to change the parent relationship for a SWG, both WGs shall approve dissolution of the relationship through respective votes and the SWG shall identify and seek approval of a new home DWG.#

[[swg-charter-approval-and-formation]]
===== SWG Charter Approval and Formation

The TCC will work with either the candidate Standard submission team or an interested group of members that wish to craft a new OGC Standard to write the draft SWG Charter. Once a draft is completed, the charter review and approval process as defined in <<approval-of-a-sub-group-charter>> shall be followed. For the purposes of charter development and approval, consider that the ad-hoc group and a submission team are equivalent in that a submission team is an ad-hoc group.

The SWG cannot begin business until the charter is approved.

Once the charter is approved by the TC and the PC, OGC staff will create a new Portal project for the new SWG. Formation of the new SWG will be announced to the membership.

Finally, the TCC shall make a general call for participation in the new SWG. The call for participation will be made public.

[[charter-members-of-the-swg]]
==== “Charter” members of the SWG

The charter members for a SWG will be:

* Any members that are part of a candidate Standard submission team;

* Any member who asks to join the SWG during the three-week SWG Charter review period; and

* Any members who participate in the development of the Charter for a new SWG.

Charter members have agreed to the IPR terms of the SWG. Charter members are immediately vested in the work of the SWG and can vote on any items or issues during the first meeting of the SWG.

[[participating-in-a-swg-opting-in]]
==== Participating in a SWG – Opting In

Any OGC member representative can join a SWG at any time and participate in the work of the SWG. If a Member wishes to participate, then the member representative(s) need(s) to “opt-in” to the new SWG in order to participate. Opting into a SWG is done via a registration page for that SWG. The registration page will be available on the OGC Portal. The registration page will clearly state the IPR terms for the SWG as well as the Scope of Work.

[lime]#From Section 3.2.1 of the OGC Intellectual Property Rights Policy:# "Any member representative opting into a SWG and making a Contribution to any SWG (regardless of its licensing designation) must commit at the time of making such Contribution that if the Proposed Standard in connection with which the Contribution is made is finally approved by OGC, the Contributor will provide a License to all patent claim(s) Owned by it that become Necessary Claim(s) by reason of its making a Contribution, without compensation and otherwise on a RAND basis, to all Implementers. Such commitment shall be made be made pursuant to a written declaration in the form of Appendix A to [the OGC] IPR Policy."

If the member representative does elect to participate (opt-in), then there is a 30-day period during which the member representative can participate but cannot vote. During this 30-day period, the member representative can also elect to opt out of the SWG and not be required to declare any IPR or essential claims.

[[swg-voting-members]]
==== SWG voting members

All of the SWG charter members can vote at the first meeting of the new SWG and are therefore deemed “voting members” of the SWG.

After the 30-day waiting period, any member representative who is not a charter member may request that the SWG chair change their status to a voting member of the SWG. Once the Chair approves the request, the member can then vote on any item or issue brought before the SWG. Any member who has been participating in a SWG for 30 days but does not wish to be a voting member can remain of group member and participate.

[[opting-out-of-a-swg]]
==== Opting out of a SWG

If during the 30-day waiting period, any member representative may elect to opt-out of a SWG without having the Member having to declare any Necessary Claims. A member representative can opt-out by notifying the TCC and/or designee representative.

[[election-of-swg-chair-and-co-chair]]
==== Election of SWG Chair and Co-Chair

The first order of business of a new SWG is to elect a Chair and Co-chair. The Chair and Co-chair must be from different Member organizations. When there are adequate nominations or volunteers for the Chair/Co-chair, the SWG Convener will call for a vote of members who have opted in to participate in the SWG. In the case where there is only one nomination for Chair and one for co-chair, the SWG Convener will ask the SWG members whether there is any objection to unanimous consent. The election of a Chair or Co-Chair can happen at either a TC Meeting or via email. The election of the Chair and Co-Chair does not require TC or PC approval. Once the election is complete, the new Chair shall notify the TCC of the results of the Chair and Co-chair election.

[[responsibilities-of-the-swg-chair-and-co-chair]]
==== Responsibilities of the SWG Chair and Co-Chair

In addition to the sub-group Chair and Co-chair responsibilities as outlined in <<role-of-subgroup-chairs>>, the SWG Chair is responsible for organizing the activities of the SWG, including the following.

* Ensuring that minutes of meetings are taken, and once approved by the SWG voting members and made available electronically to the SWG membership within two weeks of the meeting. Minutes must include:

** A list of persons attending the meeting and determining if there is quorum;

** A list of motions, seconds, and outcomes; and

** A section that details specific actions taken by members of the subgroup.

* Reporting on subgroup activities to the TC and if the SWG meetings during a TC meeting, presenting at the closing TC Plenary, including presenting subgroup recommendations (if any). Any reports to the TC SHALL be approved for release by the SWG voting members.

* Maintaining SWG member status on the Portal (voting, observer, etc).

* Ensuring that issues are logged into the Portal and these issues are prioritized and put into a roadmap for completion of a revision (or a future revision). Further, that the Chair ensures that the pertinent Standard roadmap is updated, agreed by consensus of the SWG members, and posted at least for each regularly scheduled TC meeting time.

* Ensuring that issues worked result in official change proposals and that only these official change proposals shall be considered by the SWG.

In the event that the Chair is not able to fulfill these duties, the Co-chair will step in and assume the leadership role until such time as the Chair is able to resume their duties. Failure of the Chair and/or Co-chair to provide these capabilities will result in the removal of the Chair and the election of a new Chair. If no suitable Chair can be located, then the work of the SWG will be considered to be non-critical and the SWG will be dissolved.

[[swg-voting]]
==== SWG Voting

SWGs operate under the same general voting rules as other sub-groups of the TC, namely Votes in an SWG follow the same guidelines as for the Technical Committee except that quorum is 1/2 of active voting members (see <<caveat-on-voting-rights-if-you-do-not-participate-on-a-regular-basis>>) unless the SWG votes to have a larger fraction be quorum. See <<subgroups-of-the-tc-electronic-voting>> for electronic votes for sub-groups of the TC. The one notable exception related to SWG votes is that only member representatives who have opted into the SWG may vote.

[[caveat-on-voting-rights-if-you-do-not-participate-on-a-regular-basis]]
==== Caveat on Voting Rights – If you do not participate on a regular basis

If you join a SWG and have voting privileges, you have a responsibility to participate in the teleconference and email dialogues. If you do not participate in the teleconferences and email discussions and vote on items and issues, you will lose your voting privileges and have your SWG member status changed from “Voting” to “Group Member”. The SWG Chair has the authority and the ability to make these changes based on the following policy.

Quorum for votes on any items or issues brought before a SWG is based on the number of voting members for that SWG. Insuring quorum at SWG meetings is a vital aspect of the SWG being able to complete its work in a timely manner. Therefore, any SWG voting member who misses two consecutive SWG meetings (teleconference, face to face, or webinar) in which votes occur or misses two consecutive email votes shall be deemed as inactive and will not count toward quorum after the second missed vote. The SWG Chair shall take roll call at the beginning of each meeting and determine quorum based on active voting members only. An inactive SWG voting member can become active again simply by attending the SWG meetings and participating. If regular attendance by a given voting member is an issue, that voting member may assign a temporary or permanent proxy to another SWG voting member or to the SWG Chair. The voting member may rescind that proxy at any time. If the voting member wishes not to assign their proxy, they can ask to change their status to "Observer" and still actively participate in the SWG.

[[cross-swg-communication]]
==== Cross SWG communication

Many technical issues discussed in a SWG will require collaboration and communication with other SWGs. As long as the voting members agree to such cross SWG communication, then an open dialogue between two or more SWGs can occur on any specific technical issue.

[[swg-work-environment]]
==== SWG Work Environment
SWGs are expected to maintain their Portal records in a complete fashion, including presentations made at SWG meetings. Presentations in TC Meetings which the SWG permits to be viewed by general OGC membership should be stored in the TC Meeting folder for that SWG or in the SWG Portal project files with a symbolic link to the TC Meeting folder. All draft documents for SWG discussion should be in the SWG files until that point those documents are to be discussed in the TC. SWG documents for TC discussion or voting are to be uploaded to Pending Documents.

[[swg-use-of-collaboration-environments]]
===== SWG use of collaboration environments
SWGs are free to use collaboration environments such as GitHub to store text of their draft Standard, link that text to developing code, track issues, and manage the document development workflow and milestones. A SWG may also vote to allow non-OGC members to participate in the development of the Standard in the collaboration environment. Note that such a vote does not grant access to non-members to the OGC Portal nor does it give those non-members voting rights for SWG approval of any work.

The collaboration environment will be under ultimate control of the OGC. For example, OGC maintains organizational structures in GitHub and SVN under which SWGs can create a project for their use. Non-OGC private repositories or projects may not be used for development of SWG deliverables.

The collaboration environment must clearly display a message on its home page (e.g., the README file in GitHub) that states the contributions to the work in the collaboration environment belong to OGC, as shown below.

_______________
The contributor understands that any contributions, if accepted by the OGC Membership, shall be incorporated into OGC Standards documents and that all copyright and intellectual property shall be vested to the OGC.
_______________

[[public-release-of-swg-documents]]
==== Public Release of SWG documents

At any time, the SWG voting members may agree to release any SWG in-progress technical document into a public forum, to another Standards organization, or to the public for comment. Such an action requires a formal SWG motion and SWG vote as per <<swg-voting>>.

[[release-of-documents-for-public-comment]]
===== Release of document(s) for public comment

At any time, the SWG can vote to release an in-progress candidate Standard for public comment. Please remember that there is the official formal 30-day public comment period. However, a SWG is encouraged to release an in-progress document early in the process in order to solicit input from the community. If a SWG votes to release a document for early public comment, it must coordinate with OGC Communications to generate a press release and properly create the Request For Comments (RFC) on the OGC website.

[[swg-task-process]]
==== SWG Task approval process

Any new work from a SWG after the primary deliverable must be approved by the TC as a new Task prior to start of that work. The new work can result in an update, extension, or profile of a Standard.

The proposed Task must be presented to the TC at a plenary. Otherwise, a PowerPoint or video presentation will be developed and posted to the Portal. This presentation should cover the key aspects of the Task, especially the scope of work, the timeline, and the technical discussion related how the work relates to the Standard(s) developed by the SWG.

Once the proposed Task has been presented to the TC, the TCC will initiate a 21 day TC and public review of the proposed Task. If comments are received in the review period, the SWG shall consider the comments and reissue the proposed Task details, if necessary.

The proposed Task will be voted upon by TC Voting Members in a Closing Plenary (see <<voting-at-tc-meetings>>) or by a two-week email vote (see <<tc-or-subgroups-of-the-tc-email-voting>>). Once approved, the Task will be added to the SWG Charter and the updated Charter posted to the SWG Portal files. The SWG may now begin work on the Task.

[[umbrella-swgs]]
==== Umbrella SWGs

From time to time, two or more existing SWGs need to collaborate and coordinate on a regular basis. In such cases, the SWGs may propose to create an umbrella SWG. To create an umbrella SWG:

* All affected SWGs shall vote to agree to participate in the umbrella SWG;

* All affected SWGs shall have the same IPR policy; and

* The existing charters for the affected SWGs shall be updated to state that the SWG is part of an umbrella SWG.

Once approved, the existing operational SWGs will be dissolved and reformed under the new IPR umbrella. All existing voting members would remain voting members in their respective SWGS. However, opting to participate in one SWG shall mean that the member is opting as an observer to all SWGs that are part of the umbrella SWG.

[[document-types-and-document-processes-of-the-tc]]
== Document Types and Document Processes of the TC

This section describes the various OGC documents and document handling processes that are the responsibility of the TC.

[[an-ogc-policy-document]]
=== An OGC Policy Document

A policy is a principle, rule or process that guide decisions to achieve rational outcome(s). The work of the OGC is guided by a number of Member approved policies and processes. These policies and processes are documented in various OGC Policies and Procedures documents. These shall be known as “Policy” documents. This TC P&P is a policy document. Policy documents are either maintained by the Members or by OGC staff. In all cases, new policy documents or revisions to existing policy documents shall be reviewed and approved by both the Technical and Planning Committees. Approval of a policy document shall follow the e-voting rules as defined in <<tc-electronic-voting>>. If the TC approves the Policy document, then a simple majority of the PC Voting Members must approve the TC recommendation.

Policy documents have version numbers that shall start at 1.0

[[the-Standards-document]]
=== The Standards Document

An OGC Standards document is the principal document type that captures the work and the consensus of the OGC membership. Standards documents must use the OGC Standards document template (with the exception of Community Standardsfootnote:[While there is not a formal requirement for a Community Standard to use the OGC document template for a Standard the OGC encourages the Candidate Standard submission team to consider using the OGC document template.]) that can be downloaded in Word format from: https://portal.ogc.org/?m=public&subtab=templates&tab=1 or which is available in the OGC GitHub repository as a series of AsciiDoc files.

OGC uses a multi-track Standards policy with three possible states: OGC Community Standard, OGC Draft Standard, and OGC Standard. These are described in <<the-two-track-Standards-process-characteristics>>.

Approval of an OGC Standard is described in <<policies-and-procedures-for-adoption-andor-revisions-of-Standards>>.

Each Standard distributed by the OGC shall include a cover page with the statement as specified in https://portal.ogc.org/public_ogc/directives/directives.php[Policy Directive 4].

Standards documents have version numbers that shall start at 1.0.

[[the-ogc-reference-model]]
=== The OGC Reference Model

The TC will periodically be asked to review and vote on the OGC Reference Model (ORM) Document. The ORM describes a framework for the ongoing work of the OGC and our Standards and implementing interoperable solutions and applications for geospatial services, data, and applications. The ORM can be found at:

http://www.ogc.org/Standards/orm

Any version of the ORM, once approved by the TC and the PC, is released as a public document.

[[discussion-papers]]
=== Discussion Papers

WGs and SCs shall often be used to hear presentations in their interest area. Further, a WG or SC can generate Discussion Papers for the industry covering a specific technology area germane to the WG’s or SC’s interest area. In either case, the WG or SC makes a recommendation to the TC for release of the document as a Discussion Paper.

Motions to approve release of a document as a Discussion Paper may originate from a WG or SC with TC approval, from a motion at a TC Plenary, or from a motion by the TCC.

While these Discussion Papers shall be distributed by the OGC, and might in fact lead to adopted Standards later, they do not represent an official position of the OGC TC or the OGC itself. Each Discussion Paper distributed by the OGC shall include a cover page with the statement as specified in https://portal.ogc.org/public_ogc/directives/directives.php[Policy Directive 5].

Discussion Papers do not have a version number.

[[white-papers]]
=== [lime]#White Papers#

[lime]#White Papers are OGC member-approved publications released to the Public that present a position on one or more technical considerations or other subjects that are germane to the work of the OGC, often including a high-level explanation of a Standards-based architecture or framework of a solution. White Papers often explain the results or conclusions of research.#

[lime]#Motions to approve release of a document as a White Paper may originate from a WG or SC with TC approval, from a motion at a TC Plenary, or from a motion by the TCC.#

[lime]#White Papers do not represent an official position of the OGC TC or the OGC itself. Each White Paper distributed by the OGC shall include a cover page with the statement as specified in https://portal.ogc.org/public_ogc/directives/directives.php[Policy Directive 5] where the word "Discussion" is replaced with the word "White" in the statement.#

[lime]#White Papers do not have a version number.#

[[public-engineering-reports]]
=== Public Engineering Reports

Any OGC Interoperability Initiative, such as a Test Bed or Interoperability Experiment, will have Engineering Reports (ER) as a deliverable. These ERs are typically posted to pending documents and presented and discussed in a WG at an OGC TC face-to-face meeting. The WG may recommend to the TC that the ER be publicly released. If approved by the TC, these documents shall be released as “Public Engineering Reports”.

While these ERs shall be distributed by the OGC, and might in fact lead to adopted Standards later, they do not represent the official position of the OGC TC or the OGC.

Motions to approve release of a document as an Engineering Report may originate from a WG with TC approval, from a motion at a TC Plenary, or from a motion by the TCC.

Each Public Engineering Report distributed by the OGC shall include a cover page with the statement as specified in https://portal.ogc.org/public_ogc/directives/directives.php[Policy Directive 6].

Engineering Reports do not have a version number.

[[best-practices-documents]]
=== Best Practice and Community Practice Documents

OGC Members, TC subgroups, or Interoperability Initiatives may generate Best Practice (BP) and Community Practice (CP) Documents for the industry covering best practices related to the use of an OGC Standard or other technology relevant to one or more OGC Standards. These documents describe a technique or methodology that, through experience, implementation and research, has proven to reliably lead to a desired result. In some cases, BPs or CPs may transition to full Standards through the OGC Consensus Standards process.

BP and CP documents have version numbers that shall start at 1.0. BP and CP documents may also have corrigenda per the process defined in <<corrigendum-errata-changes-to-ogc-Standards>>.

*Best Practice:* a document describing the use of one or more OGC Standards, typically to address a domain-specific topic or provide a solution to an interoperability challenge. Best Practices may also describe implemented extensions to or profiles of OGC Standards.

*Community Practice:* a document describing implemented Standards, specifications, or technologies that originate outside of OGC, but which are relevant to address interoperability requirements in the geospatial and related communities.

[[submission-of-documents-to-be-considered-as-an-ogc-best-practice]]
==== Submission of documents to be considered as an OGC Best Practice or Community Practice

In order to be considered for approval as an OGC BP or CP, the document submitters shall provide the following.

* An Abstract or Introduction in the document explaining why a submitted document is relevant to the OGC.

* Evidence of implementation. Evidence of implementation shall include but not be limited to: Implementation in commercial product, implementation in open source applications or software, and/or implementation in deployed applications. A single research related implementation is not proper evidence of implementation.

* [lime]#TC and Public Request for comment of 30 days.#

* Presentation of the contents of the proposed BP at an OGC face-to-face meeting. The presentation may be done remotely using OGC communication tools, such as GoToMeeting.

* Post the document to OGC Pending Documents on the OGC Members Portal for at least three weeks prior to the face-to-face [lime]#or remote# presentation.

[[approval-of-ogc-best-practice-documents]]
==== Approval of OGC Best Practice and Community Practice Documents

Both document types are an official OGC position statement. Therefore, BP and CP Documents shall be approved by formal electronic vote. Motions to initiate a BP and CP e-vote may originate from a WG with TC approval, from a motion at a TC Plenary, or from a motion by the TCC.

A BP and CP vote has the same rules as a Standards adoption vote (<<tc-electronic-voting>>).

The BP and CP document authors shall respond in writing (email is acceptable) to any comments received during the voting period. If necessary, the document authors shall edit the document. If the TCC deems that the edits to the document are more than editorial, then the document shall be posted to pending and a new BP or CP approval e-vote shall be initiated.

Each BP and CP distributed by the OGC shall include a cover page with the statement as specified in https://portal.ogc.org/public_ogc/directives/directives.php[Policy Directive 7].

[[documents-and-distribution]]
=== Documents and Distribution

The numbered document (see <<document-numbers>>) as distributed to members is to be considered the official document of the TC. Electronic mail shall be used for day-to-day discussion of OGC documents. The preferred mechanism for document sharing is the OGC Members-only Portal. OGC Communication shall be used for announcing the availability of new official documents. The actual documents will not be distributed by email unless a member requests receiving a document by email. All official documents will be posted to the Portal. Other electronic forms of documents can be made available at the written request of members.

The Members section of the OGC Portal (http://portal.ogc.org) shall provide the default method of disseminating documents in electronic form. The TCC or his designee shall determine the electronic distribution formatfootnote:[Typically, official documents are provided to the public in Word “.doc” format or Adobe PDF format. However, various presentations, draft documents, and so forth can also be distributed in PowerPoint format, HTML, and other formats as provided by the Members. The TCC reserves the right to reject a document that is in a non-industry Standard distribution format.] of these documents. OGC Consensus Standards proposals, Discussion Papers, Best Practices Documents, and Engineering Reports must be provided in one of the formats defined in <<other-document-concerns>>. However, the preferred document format is the Word .doc format. The format for dissemination may change as distribution technology changes. Up until mid 2014, all approved Abstract Specification Topics and Standards were only available in PDF format. Please note that the OGC has moved to publication of OGC Standards documents in HTMLfootnote:[Initial publications in 2014.].

[[document-numbers]]
==== Document Numbers

All member submitted documents shall be assigned a document number. Members can obtain pending document numbers using the members only Portal, OGC Pending Documents page located at https://portal.ogc.org/?m=public&orderby=default&tab=1.

Instructions for obtaining a Pending Document number and posting the document can be found at https://portal.ogc.org/?m=public&subtab=instructions&tab=1.

[[document-version-numbers]]
==== Document version numbers

The guidelines for version/revision numbers for documents are as follows.

* All non-specification/Standards documents do not have version numbers at publication.

* Only approved OGC Standards have document numbers 1.0.0 or greater. The first approved version of an OGC Standard shall be version 1.0.0.

* Corrigendum releases shall NOT result in any change to the major/minor number. If the Standard being revised has schema, then the schema shall use the version attribute to document the revision number at the third level.

* Revisions to an adopted Standard typically result in a change to the minor number. For example, the first revision to an adopted 1.0 Standard would be 1.1.0. Minor revision releases should be 100% backwards compatible with the previous version.

* Changes to the major version number are reserved for when there are significant changes to the adopted Standard or when backwards compatibility cannot be maintained with the previous version.

See also https://portal.ogc.org/public_ogc/directives/directives.php[Policy Directive 18].

[[change-proposal-format]]
==== Change Proposal Format

Change Proposals for any OGC document shall use the procedures and format as documented in <<change-request-proposals-crp-to-an-ogc-document>>.

[[other-document-concerns]]
==== Other Document Concerns

All documents with official OGC Document Numbers that are to be considered and discussed at a TC face to face meeting shall be made available electronically to all members at least three (3) weeks before the next TC meeting. However, this clause does not apply to informational documents for which there will not be any motions or actions. Numbered documents shall be posted to https://portal.ogc.org/index.php?m=public&orderby=default&tab=1[Pending Documents].

The TC will enforce this policy under the conditions described for the <<three-week-rule>>.

All documents shall be made available in one or more of the following formats:

* Microsoft Word including .docxfootnote:[Microsoft provides conversion tools for backwards compatibility.] format (preferred),

* Rich Text Format (RTF),

* Portable Document Format (PDF),

* Hypertext Markup Language (HTML),

* Microsoft PowerPoint (preferred for presentations),

* Microsoft Excel (preferred for tabular information such as lists of URLs),

* AsciiDoc, or

* ASCII Text.

[[policy-for-the-retiring-deprecating-or-rescinding-ogc-documents]]
==== Policy for the Retiring, Deprecating, or Rescinding OGC Documents

This section provides the policy and procedure for retiring, deprecating, or rescinding OGC documents. Note that retiring, deprecating, or rescinding an OGC Standard results in the same fate for all extensions to that Standard; such a fate is version-dependent: only the extensions specific to the exact version of the Standard being retired, deprecated, or rescinded will share that fate. Deprecation of a Standard does not automatically result in the deprecation of a profile of that Standard.

[[retiring-ogc-documents]]
===== Retiring OGC Documents

"Retirement" criteria can be based on one or more of the following:

* A document is no longer technically up to date;

* A document is not actively downloaded from the OGC website;

* A document is no longer considered to be of interest by the Membership;

* The document is no longer valid due to new OGC documents being published; or

* For a Standard, no one is implementing the Standard.

At the one-year anniversary for a Discussion Paper, the two-year anniversary of a Public Engineering Report and at the three-year anniversary of any Standards documentfootnote:[If a Standards document is retired, any associated Best Practice document shall automatically be retired,], the OGC shall determine whether the document should be retired or remain an active Member document. The TCC shall compile a list of such documents prior to any OGC Face-to-Face meeting. The OGC Staff shall also compile download statistics. This information shall be compiled into a single document, posted to pending documents, and an announcement of availability broadcast to the Membership.

For discussion papers, public engineering reports, and best practices, the TCC shall create a set of motions related to documents for consideration for retirement by the TC Membership. The form of the motion shall be:

“The TCC recommends that OGC document <xyz> remain an active OGC document.”

A positive vote indicates that the document shall not be retired. These motions shall be presented at the closing plenary at a TC meeting. Based on the results of the vote, the target documents shall either be retired or remain active.

In the case of a OGC Standard, a formal electronic vote by the TC Voting Members is required to approve retirement.

Retired documents are not removed from the OGC public website. Instead, they are moved from the current document archive to the "Retired" archive. Further, any retired document shall have “Retired” watermarked on the cover page. If there are schemas associated with a retired OGC Standard, the schemas remain in the OGC schema repository. If there are compliance tests for the retired Standard, the compliance tests are automatically retired but also remain available on the OGC web site.

[[deprecating-ogc-Standards]]
===== Deprecating OGC Standards

OGC policy documents may be deprecated by vote of the TC. A deprecated document is no longer supported, but is made available to the public on the OGC website and other resources.

* In the case of Policies and Procedures, approval of a revision automatically deprecates the previous version.

* Standards and Best Practices may be deprecated by vote of the TC. Deprecation must be preceded by a 60-day public comment period informing the community that the Standard is proposed for deprecation and requesting evidence to support or reject deprecation. Any comments received during the public comment period must be presented to the TC during the request to deprecate the Standardfootnote:[The deprecation public comment period can start at any point prior to requesting approval of the revised Standard. Such a review of the impact of deprecation should begin as soon as a SWG considers a revision that is intended to result in a deprecation of a Standard.]. Where the document is proposed for deprecation because a new version of the document is to be approved, the deprecation vote may be part of the adoption vote for the new document. In this case, when the motion is made to the TC at a face-to-face meeting or email vote to approve the start of an electronic vote for a Standard or Best Practice, that motion shall include a request to deprecate the previous version, if the previous version is recommended for deprecation by the WG. Where the document is proposed for deprecation and no future version is in consideration, then an electronic vote is required as described for <<retiring-ogc-documents>>.

[[deprecating-api-elements]]
===== [lime]#Deprecating API elements in OGC Standards#

[lime]#Standards for APIs (Application Programming Interfaces) are specifically designed to be implemented as a series of API elements. These elements may be described in a format more suitable for direct use by software developers (such as OpenAPI content delivered in YAML). Elements with the API description correspond to one or more requirements defined in the Standard document.#

[lime]#When an API element is removed during the <<the-Standard-revision-process-full-Standard>>, the impact on implementations of that Standard should be minimized. Therefore, the implementing community will be given sufficient notice and provided with options for commenting on the changes to the Standard through a formal API element deprecation process.#

[lime]#The API element deprecation process is as follows.#

[lime]#1.  A candidate revision to the Standard and any supporting API definition resources is provided to the TCC with all proposed deprecated elements clearly identified. The rationale for deprecating the elements is provided as a separate document. Optionally included with the rationale can be work-arounds or other documentation to describe how implementers might address the changes to the Standard.#

[lime]#2.  The candidate revision is released for a 60-day public comment period informing the community that the Standard is proposed for revision with deprecation of some API elements. The call for comments will request the community to provide evidence to support or indicate the consequences of deprecating the API elements.#

[lime]#3.  The SWG will consider all comments received per the process for <<review-of-the-received-comments-all>>. Based on the comments, the SWG will decide whether to proceed with the revision.#

[lime]#4.  The candidate Standard with all deprecated API elements clearly identified as deprecated continues the Standard approval process.#

[lime]#5.  Once approved, the Standard retains the deprecated API elements, each clearly identified as deprecated, in the publication for a period of two years. After two years, the deprecated API elements may be removed from the published document. If there is another revision to the Standard before the two-year period ends, the deprecations will still be identified in the revision until the original two-year period ends.#

[[rescinding-ogc-Standards]]
===== Rescinding OGC Standards

OGC Standards may be rescinded for three reasons:

1.  The Standard includes intellectual property that was unintentionally or illegally provided as part of the Standard;

2.  A Community Standard is abandoned by its originating/maintaining party and the OGC membership does not take-over maintenance of that Community Standard; or

3.  A Community Standard is judged by OGC membership to no longer be applicable to the OGC Mission.

A Standard is rescinded by electronic vote of the TC as described for <<retiring-ogc-documents>>.

[[policies-and-procedures-for-adoption-andor-revisions-of-Standards]]
== Policies and Procedures for Adoption and/or Revisions of Standards

This section covers procedures for adoption, revision, and maintenance of OGC Standards. For the purposed of clarity, the term “Standards” covers both the candidate abstract and implementation cases.

[[Standards-proposed-for-adoption-caveats]]
=== Standards Proposed for Adoption – Caveats

Only Voting TC Members of the OGC may propose candidate Standards for adoption by OGC.

All adoption votes to approve a document as an OGC Standard shall be electronic. Only Voting TC Members may vote on an adoption vote. However, any OGC member, regardless of membership level, can 1.) be part of a team submitting a candidate document and 2.) join a SWG and work on a candidate Standard.

The TC e-vote is to recommend to the PC approval of the results of an adoption vote. This will ensure that all TC voting members have the opportunity to vote on the most important work done by the Consortium. Lack of a vote does not count as a vote of Abstain; only an actual vote of Abstain counts as such a vote.footnote:[It is felt that this most important TC vote should encompass the entire Voting TC membership, rather than a portion of a meeting quorum, to allow all OGC Voting TC Members to have control over the issue. Note that the TCC does not cast a vote in the specification adoption process as the TCC vote may only be used in the case of a tie. Under the rules of the new OGC IPR policy, all Specification votes will be by electronic vote. As such, the entire TC voting membership will have the opportunity to vote.]

The policy of the OGC is that proposed Standards resulting from a OGC Consensus Standards process evaluation may be recommended to the PC for acceptance conditional on certain changes to the Standard, which the TC deems necessary, within a specified time frame.

Acceptance of the TC recommendation for adoption is always with the caveat that the PC may verify that the Standard's sponsor organization(s) is/are in a position to develop (or have developed for the sponsor organization) or commercialize an implementation of the Standard. Further, for candidate Standards developed external to the OGC and submitted into the OGC process, the PC may verify that the submitting organization has provided a duly executed submission of technology form. In addition, the TC recommends acceptance contingent on the PC’s finding that the sponsoring organization(s) makes the technology available as per the OGC Intellectual Property Policies and Procedures.footnote:[It was felt that it is not within the TC's purview to determine the ability or intent of an OGC member and technology sponsor to commercialize a technology. However, it was felt that the TC's work would be fruitless without such ability and intent. Therefore, recommendations to the PC shall implicitly or explicitly include such caveats.]

[[the-two-track-Standards-process-characteristics]]
=== The Two Track Standards Process: Characteristics

There are two possible tracks for proposing and approving candidate Standards or proposing and approving revisions to an existing adopted Standard: The OGC Community Standard and the OGC Full Standard track. These two tracks are described below. Regardless of the submission track, the OGC Consensus Standards Process shall be used. There are key differences in the OGC Consensus Standards process depending on whether the Community or the Full Standards track is being used. The following table summarizes the key aspects and steps in the OGC Consensus Standards process for the two tracks.

[cols=",,,,,,,,,",]
|==================================================================================================================================
| |SWG |Evidence of Implementation |Modular Spec |Compliance Test |OGC Template |Public Comment |OAB Review |IPR to OGC |Member Vote
|Community Standard |NR* |Strong |NR* |Partial |Yes |Yes |Yes |Yes or Shared |Yes
|Full Standards Track |||||||||
|Draft Standard |Yes |No |Yes |NR* |Yes |Yes |Yes |Yes |Yes
|Standard  |Yes |Yes |Yes |NR* |Yes |Yes |Yes |Yes |Yes
|==================================================================================================================================
*NR - Not required.

Community Standard: This is a document, developed by communities external to the OGC, such as GeoRSS, that OGC members wish to bring into the OGC process. The key consideration for a Community Standard submission is that there is very strong evidence of implementation. At the same time, the community owning the Standard may not want to allow normative changes (except for errors) to the document, may not wish to follow the OGC Modular Specification Policy, nor do they wish to develop CITE tests. Please visit Section 9.5 and Annex C to read more about the requirements for submitting a Community Standard as well as a checklist of steps in the Community Standard submission, review, and approval process.

Full Standards track, which consists of two possible target levels of Standard.

Draft Standard: This is a document developed by the OGC membership for which there is no evidence of implementation or CITE tests. However, the members wish to approve the document as an official OGC document in order to have developers and organizations implement the Draft Standard and provide feedback. A Draft Standard is uplifted to a Standard once evidence for implementation is provided. A Draft Standard is often derived from output of requirements discussions in DWGs, results of Innovation Program activities, and/or the OGC Technology Strategy which links key innovation activities to anticipate Standards needs for emerging technologies.

Standard : This is a mature OGC Standard for which there is evidence of implementation This is the final stage in the Full Standards track.

[[two-track-Standards-process-criteria]]
==== Two Track Standards Process Criteria

Evidence of implementation: The TC will judge whether the evidence of implementation for a particular Standard is sufficient to warrant approval of that Standard. Strong evidence of implementation as required for the Community Standard is generally defined to be implementation in multiple products or environments OR widespread use of the Standard in a community, even if in only one or a limited number of products or environments. Evidence of implementation for a Standard in the Full Standards track is defined as three or more documented implementations that meet the Nature of implementation criteria, below. The TC may choose to override the minimum number of implementations for a specific candidate Standard by specifying a lesser number in the electronic adoption vote.

Nature of implementation: API, service, and exchange protocol Standards shall have as evidence of implementation running services which deliver content to another machine (including client software). Encoding Standards shall have as evidence of implementation data sets containing content representative of the Standard, but not necessarily containing an example of every element in the Standard.

Conceptual model evidence of implementation: a Standard that is conceptual in nature (e.g., cannot be implemented directly) and not being advanced as an Abstract Specification Topic shall only be advanced from a Draft to a final stage once at least one implementation Standard based on the conceptual model is approved at the Draft stage.

Abstract Specification Topics: these Standards do not require evidence of implementation due to their foundational nature. Abstract Specification Topics are approved as Standards without a Draft stage.

Modular Specification: compliance with the Modular Specification is evidenced by inclusion of clearly defined Requirements and an Abstract Test Suite in the Standard document. The OAB will evaluate a Standard against this criterion.

IPR: Community Standard may contain IPR that is jointly held by the OGC and the submitting organization. The Full Standards track requires that OGC hold the IPR.

[[status-of-Standards-approved-before-the-two-track-Standards-process]]
==== Status of Standards Approved Before the Two Track Standards Process

OGC Standards approved prior to the effective date of Revision 24 of these Policies and Procedures (05-020r24) will automatically be classified as “Standards” under the Full Standards track.

[[adoption-andor-revision-to-a-Standard---general]]
=== Adoption and/or Revision to a Standard - General

The OGC Consensus Standards Process (<<policies-for-the-Standard-process>>) is the only way for a candidate Standard to move through the review and approval process. This is the approach for proposing a new candidate Standard, submitting an externally developed community specification into the OGC process, extensions to an existing Standard, profiles of an existing Standard, or an application schema for consideration by the membership. For the Full Standards track, a SWG manages the OGC Consensus Standards process.

Please note: A new Standards activity can also be initiated when there are outstanding change request proposals. Change Request Proposals (CRPs) (<<change-request-proposals-crp-to-an-ogc-document>>) provide details for revisions to existing Abstract Specifications or Standards. A CRP describes proposed changes or enhancements to an existing Standard. A CRP may be submitted by one or more OGC member organizations. One or more CRs against an existing OGC Standard is evidence that a revision process for that Standard should be initiated. In this case, the TCC may request members consider a Standards activity using the OGC Consensus Standards process.

The following section provides details on the OGC Standard development processes.

[[policies-for-the-Standard-process]]
=== Policies for the OGC Consensus Standards Process

The following sections details the requirements, policies, and procedures for adoption of a candidate Standard using the OGC Consensus Standards process. Each section specifies whether that step or requirement in the process is for All submissions, Community Standard only, or Full Standards track only. Please also refer to  <<annex-b-Standard-process-outline-full-ogc-Standard>> of this document for a synopsis of the steps in the OGC Consensus Standards process for the Full Standards track.

[[conditions-for-submission-of-an-candidate-Standard]]
==== Conditions for Submission of a Candidate Standard

Any OGC Technical Committee Voting Member may make an unsolicited submission of a candidate Standard or a proposal for the development of a new candidate Standard using the OGC Consensus Standards process given that for the submission, the following conditions are met.

* Three different Member organizations endorse the submission; evidence of the endorsement via a letter or email to the submitter must be provided to the TC Chair.

* A Voting Member is the lead for the submission team.

* For a candidate Community Standard, there is evidence of implementation and evidence of a continued commitment to commercialize and/or support the implementation.

* For a Community Standard, the submission team completes a written justification as to why the Community Standard track is being requested. This step is described in more detail below.

* All required documents (see below) must be ready for submission to the OGC for consideration through a OGC Consensus Standards process.

[[intent-to-submit-an-candidate-Standard-all]]
==== Intent to Submit a Candidate Standard (All)

Any organization that intends to submit a candidate Standard via the OGC Consensus Standards submission process must inform the TCC via email or written correspondence that a new candidate Standard is being submitted. At least three different OGC Member organizations must commit to being part of the submission team. The primary submitter must be a TC Voting Member. The TCC will announce via OGC Communications that there is intent to submit a candidate Standard.

[[terms-and-conditions-for-candidate-Standard-submissions-all]]
==== Terms and Conditions for OGC Candidate Standard process submissions (All)

In the OGC Consensus Standards process, the submitters agree to the following set of terms and conditions.

* For a Community Standard, work with OGC Staff to develop and submit a justification for submitting a candidate community Standard.

* For a Full Standards track submission, work with OGC staff to develop a new SWG Charter or to revise the Charter of an existing SWG.

* All OGC Consensus Standards process submissions originating from work done external to the OGC consensus process and then submitted into the OGC for consideration as an OGC Standard may require a signed original of the OGC Submission of Technology Formfootnote:[If a candidate Standard is developed entirely within the OGC process, then a SoT is not required.]. Work with OGC staff to determine if a SoT form is required. This form shall be provided to the OGC prior to the adoption vote.

* The Submission team has reviewed the current Policy Regarding Intellectual Property Rights of OGC and agrees that its submission is being made in full compliance with those Policies.

* Proprietary and confidential material may not be included in any submission to the OGC.

* OGC Candidate Standard submitters must provide an agreement to grant OGC a non-exclusive, royalty-free, paid-up, worldwide license to copy and distribute their submission to the OGC membership, and, if adopted by OGC, the right to modify, enhance, and make derivative works from the Standard and to copy and distribute the Standard, modifications, enhancements, and derivative works both inside and outside of the OGC membership.

* The Submitters agree that the OGC may copy, distribute and otherwise make available this submission for the purpose of evaluation, and that in the event that the submission is accepted, that OGC will own the copyright in the resulting Standard or amendment and all rights therein, including the rights of distribution. This agreement shall not in any way deprive the Submitter of any patent or other IPR relating to the technology to which its submission relates.

* OGC Standards may reference other OGC Standards or Standards from other Standards organizations. Incorporating Standards by reference requires that the Standard clearly designate what portions of the other Standard are referenced, the version of the other Standard, a complete reference to the other Standard, and complete information on how to obtain the other Standard. Whenever possible, submitting organizations are asked to make available to OGC the referenced Standard in soft or hard copy form.

[[specific-process-requirements-for-the-submission-of-a-community-Standard-cs]]
==== Specific process requirements for the submission of a Community Standard (CS)

[[notify-tc-chair]]
===== Notify TC Chair

The submission team shall notify the Technical Committee Chair of the intent to submit a Community Standard. This notification may be done using email. The notification shall include the organization names of the submission team. The notification shall also include agreement to the following statement:

The companies <list of companies/organizations> have granted the Open Geospatial Consortium (OGC) a nonexclusive, royalty free, paid up, worldwide license to copy and distribute this document and to modify this document and distribute copies of the modified version.

[[submission-justification-document-process]]
===== Submission justification document process

The submission team shall provide a written justification as to why the Community Standard process can be used. This justification shall also include the reasons why the candidate Standard may not need to be aligned with the OGC Abstract Specification and Standards Baseline. There is a template for this justification (OGC 16-113, Community Standard Justification Template).

Once the submission team completes a draft of the justification document, they shall provide the TCC the draft. The TCC shall review the draft and provide comments and guidance back to the submission team. The Submission Team reviews the TCC comments and modifies the justification as required. When the Submission Team agrees that the justification document is complete, the convener shall post the justification document to pending documents. The document shall be posted as a Public document.

[[submission-justification-document-member-review-process]]
===== Submission justification document: Member review process

Once the justification document is posted to pending, the TCC shall:

* Announce a three week OGC Member review period. Comments may be provided.

* Coordinate a broad community announcement that the OGC is considering accepting a Community Standard into the OGC Standards process; and

* Have the proposed Community Standard submitters present the justification to the TC at a Plenary or via a web meeting and ask the full TC if there are any objections to starting an electronic vote on the proposed candidate Community Standard as an official OGC work item. If there are objections, comments shall be provided.

[[approval-of-the-proposed-community-Standard-as-an-ogc-work-item]]
===== Approval of the proposed Community Standard work item

Upon completion of the review and comment process, the TCC shall initiate an official e-vote to approve (or not) the proposed work item for processing a Community Standard. This vote shall follow the e-vote process and policies as defined in <<tc-electronic-voting>> of the OGC Technical Committee Policies and procedures. If the approval motion fails, the submission shall be withdrawn and the submission team may resubmit the candidate community Standard after addressing Member concerns. A Community Standard Work Item is valid for six months: within this time period the draft Community Standard must be scheduled for OAB review or else the Work Item must be renewed through a new submission.

[[processing-comments-received-during-the-community-Standard-work-item-approval-vote]]
===== Processing Comments received during the Community Standard work item approval vote

If comments are received as part of the approval vote for using the Community Standard process, the submission team shall follow the process as defined in <<review-of-the-received-comments-all>>.

[[required-components-of-the-Standard-submission-package]]
==== Required components of the OGC Consensus Standards process Submission Package

In addition to the candidate Standard document, all OGC Consensus Standards process submissions must include a signed Cover Letter and if required a signed OGC Technology Submission form for each submission.

[[submission-cover-letter-all]]
===== Submission Cover Letter (All)

The lead organization on each OGC Consensus Standards process submission shall provide a Cover Letter stating the intent of the organization to support the SWG and related OGC Consensus Standards process. The cover letter may be in the form of an email correspondence.

[[ogc-technology-submission-form-externally-developed-submissions-only]]
===== OGC Technology Submission Form (Externally developed submissions only)

The following clause applies to candidate Standards developed external to the OGC and then submitted by the Members for consideration as an OGC Standard.

Assurances are required at the time of submission that the Intellectual Property Rights inherent in the submissions will, if the submission is approved as an OGC Standard, be made available under license to all implementers, members and non-members alike.

In order to assure this result, any organization submitting a OGC Consensus Standards process Proposal Package where the candidate Standard was developed outside the OGC SWG or DWG process may be required to complete, sign and deliver a Submission of Technology Form (SoT). Please contact OGC staff to discuss whether a SoT is required. If required, the signed SoT shall be provided prior to the adoption vote.

[[additional-member-endorsements-all]]
===== Additional Member endorsements (All)

Any submission requires that three or more distinct Member organizations support the submission. In addition to the submission team lead, each other organization supporting the submission shall provide the TCC with an email stating their organization’s support of the submission.

[[main-steps-in-the-Standard-process]]
==== Main Steps in the OGC Consensus Standards Process

The steps in the OGC Consensus Standards Process are as follows.

[[submission-of-the-Standard-package-to-the-ogc-all]]
===== Submission of the OGC Consensus Standards process package to the OGC (All)

The OGC Consensus Standards process Submission team shall provide the submission package to the OGC TCC. The TCC shall review the proposal in terms of required documents.

For a Community Standard, the submission package shall include:

* Cover letter,

* Endorsements,

* Justification document (see <<submission-justification-document-process>>),

* Agreement in writing that the OGC has rights to use, modify, copy, and distribute the candidate Standard (See <<ogc-technology-submission-form-externally-developed-submissions-only>>), and

* Candidate Standard document.

For a Full Standard, the submission package shall include:

* Cover letter,

* Endorsements,

* SWG Charter (See below), and

* Candidate Standard document if one exists. For proposed new Standard, providing a document is not required.

Documents being submitted as Full Standards shall use the https://portal.ogc.org/files/?artifact_id=56777/[document formatting and content], in common use by the OGC at the time of submission, of Standards submitted under the OGC Consensus Standards process. There is a detailed https://portal.ogc.org/files/?artifact_id=3244/[guidance document] for using the template.

Documents being submitted as Community Standards do not need to follow the OGC document template for an OGC Standard. However, the submission team for a Community Standard is strongly encouraged to provide the candidate Standard to the OGC using the document template.

Proposals that require changes to the Abstract Specification must include acceptable documentation (at the discretion of the OGC TC) of these changes.

[[formation-of-a-new-swg-to-work-on-the-Standard-submission-full-Standard]]
===== Formation of a new SWG to work on the OGC Consensus Standards process submission (Full Standards)

See <<swg-charter-approval-and-formation>> on the Policies specific to the formation of a new SWG and SWG processes.

[[release-of-candidate-Standard-for-internal-review-and-public-comment-all]]
===== Release of candidate Standard for internal review and Public Comment (All)

At any time in the OGC Consensus Standards process, the SWG may vote to release a candidate Standard for public comment. These interim public comment periods do not require OAB review or OGC Naming Authority review. However, there shall be at a minimum one official 30 day public comment period.

Full Standard: Once the SWG determines that the candidate Standard is ready for OAB and OGC-NA review and public comment, the SWG shall have a vote to release the document for public review. Upon a simple majority vote by the voting members of the SWG, the candidate Standard will be released for a 30-day public comment period. The OAB shall review a candidate Standard prior to the actual release for public comment.

Community Standard: The community Standard submission team and the TCC must agree that the candidate Standard is ready for review and the TCC will submit the candidate Standard for internal review by the OAB and OGC-NA.

[[review-by-the-ogc-architecture-board-all]]
===== Review by the OGC Architecture Board (All)

Once the SWG or Community Standard submission team approves the candidate Standard for public comment, the candidate Standard is reviewed by the OAB. The OAB has the responsibility to ensure that the OGC candidate Standard submission is relevant in terms of the rationale for how the candidate Standard fits into the current adoption plans of the OGC (and/or the current Abstract Specification), for Full Standards compliance with the Modular Specification Policyfootnote:[https://portal.ogc.org/files/?artifact_id=34762[_The Specification Model - A Standard for Modular specifications (08-131r3)_]], and how the proposal is consistentfootnote:[This information is to be provided in the Community Standard Justification document. A Community Standard is not required to align with the current OGC Standards baseline or may overlap existing OGC Standards functionality.] with the current OGC Standards baseline. The candidate Standard cannot be released for public comment until it is approved for release by the OAB. The OAB may request changes to be made to the candidate Standard and have that document returned to the OAB for further review.

[[review-of-ogc-identifiers-http-uris-etc-by-the-ogc-naming-authority-all]]
===== Review of OGC Identifiers (http URIs, etc) by the OGC Naming Authority (All)

Concurrent with the OAB review of the candidate Standard, the SWG shall provide a list of all new OGC identifiers specified in the candidate Standard to be issued for persistent public OGC resources. This list shall be submitted to the OGC Naming Authority for review. This submission may be done by email. The specific policy is specified in the http://www.ogc.org/ogc/policies/directives/[TC Policy Directives].

The candidate Standard document/repository will also be provided to the OGC-NA to ensure that document tags and formatting are consistent with the OGC Standard template and suitable for ingestion into the OGC Knowledge Management database.

In order to facilitate the review and to be in compliance with the OGC http URI policy [OGC 06-135 – Directive 21], the editor shall submit the candidate Standard’s list of docfootnote:[As specified in OGC 09-046, 09-047, and 09-048 (latest versions) found at http://www.ogc.org/ogc/policies/directives], spec and XML Namespace URIs for OGC-NA review formatted into an Excel spreadsheet or as a Persistent Uniform Resource Locators (PURL)footnote:[http://purl.oclc.org/docs/index.html] configuration document, which is valid according to the batchPurls.rng schema.

[[release-for-public-comment-period-all]]
===== Release for Public Comment Period (All)

The candidate Standard is released for a 30-day public comment periodfootnote:[The SWG may determine that a longer comment period is required.]. During the RFC comment period, any party (including all classes of OGC members, as well as any non-member of OGC) may send comments on the proposal to OGC Headquarters or to the address announced with the RFC issuance. OGC staff will manage collection of the comments. OGC Communications will insure that the SWG or Community Standard submission team membership is informed regarding submitted comments. It is important to note that anyone may make a comment on an outstanding RFC. RFC’s are available to the public, not just members, and are publicized.

[[review-of-the-received-comments-all]]
===== Review of the Received Comments (All)

Once the RFC comment period closes, the candidate Standard submission team “collects” the comments and integrates them into a single RFC comment document. The team reviews the comments and determines how each comment will be responded to. The team may decide to:

* Accepts the comment as is and edits the candidate Standard accordingly;

* Accepts the comment with modification and edits the candidate Standard accordingly;

* Accepts the comment as a future work item; or

* Rejects the comment with an associated reason.

NOTE: the team cannot accept a comment that makes a normative change to a Community Standard unless the comment identifies an error. A Community Standard is normatively-frozen once it enters the approval process.

In all cases, the team shall document their decision in the RFC comment document. Further, the team shall notify each individual who submitted a comment as to the disposition of the comment. This could be done by pointing the individual to the public comment response document.

The comment response document shall be a public document. The comment responses can be provided in a document or a Wiki.

Finally, the team may need to make a decision as to the fate of the OGC Consensus Standards process. If the team decides that comments received are sufficient to halt the OGC Consensus Standards process, then the OGC Consensus Standards process "fails" and adoption of the proposal halts. The submitter(s) may then make changes and resubmit the OGC Consensus Standards process proposal.

If, however, the comments received do not cause the team to halt the OGC Consensus Standards process, then the team edits the document based on the comments received during the comment period (See above).

If the RFC comments result in a significant change to the candidate Standard, then the TCC may request that the revised candidate Standard be reviewed by the OAB once more prior to the TC adoption vote.

[[member-briefing-for-candidate-Standard-all]]
===== Member briefing for Candidate Standard (All)

Once the final document has been posted to pending, the submission team shall brief the TC Membership on the contents of candidate Standard. This briefing shall occur prior to a final adoption vote. This briefing may be at a face-to-face meeting or via an official OGC GoToMeeting session (webinar). The briefing shall be announced via formal OGC communications at a minimum of three weeks prior to the briefing. Further, if the briefing is via a webinar, the submission team shall identify two separate dates and times for the briefing. This is to accommodate OGC members in all time zones. Alternatively, the submission team may create a video of a briefing and make this video available to the OGC membership.

[[vote-to-approve-candidate-Standard-all]]
===== Vote to Approve Candidate Standard (All)

After the candidate Standard has been briefed to the TC, the TCC will request that the TC approve the start of an electronic vote to recommend approval of the candidate Standard by the PC. This vote can occur in a Plenary (see <<votes-that-can-occur-in-a-tc-plenary>>) or via email (see <<tc-or-subgroups-of-the-tc-email-voting>>).

Upon approval of the TC to start an electronic vote, the TCC will initiate a 45-day electronic vote to recommend approval of the candidate Standard by the PC. This vote will follow the rules specified in <<tc-electronic-voting>>.

A YES vote by the TC to recommend approval by the PC will initiate a PC vote, further described in the PC Policies and Procedures.

[[specific-policies-regarding-approval-of-a-Standard-uplift]]
==== Specific policies regarding approval of uplift of a Draft Standard to a Standard

A Draft Standard proposed to be approved as a Standard must be submitted by the SWG to the TCC with written documentation that the Standard meets the criteria for evidence of implementation per the <<two-track-Standards-process-criteria>>. The candidate Standard must then proceed with the RFC (<<release-for-public-comment-period-all>>) through Voting (<<vote-to-approve-candidate-Standard-all>>) steps.

[[specific-policies-regarding-profiles-moving-from-a-best-practice-to-a-Standard]]
==== Specific policies regarding profiles moving from a Best Practice to a Standard

In the case where an OGC-approved Best Practice is a profile of an active Standard (i.e., not retired, deprecated, nor rescinded) and members wish to submit the profile for adoption as a full Standard, the Standard approval process is modified as follows.

NOTE: if the Best Practice is a profile combined from multiple Standards, then the profile must be advanced as a Standard via the normal full Standards track process. The single Standard to which the profile applies may itself have normative references to other Standards; such a situation does not make the profile “combined from multiple Standards.”

1.  The submitters of the Best Practice must agree to proceed with the Standard adoption process.

2.  The SWG responsible for the parent Standard (i.e., the Standard to which the profile applies) must vote to proceed with the Standard adoption process per the normal SWG processes and voting rules.

3.  The candidate Standard is reviewed by the OAB and the OGC-NA.

4.  The candidate Standard will be assessed against the same criteria applied to the parent Standard. For instance, if the parent Standard was approved prior to publication of the Modular Specification, then the candidate Standards will not be required to be compliant with the Modular Specification.

5.  The candidate Standard is released for a 30-day simultaneous TC and public request for comment.

6.  Comments are reviewed and addressed by the submitters to the satisfaction of the TCC.

7.  The candidate Standard is voted upon by the TC and PC per <<vote-to-approve-candidate-Standard-all>>. Note that the Best Practice was already approved by the TC and PC, so a presentation to and request to start a vote from the TC will not be required.

[[specific-policies-regarding-abstract-specification-topics]]
=== Specific Policies Regarding Abstract Specification Topics

The OGC Abstract Specification Development, Revision, and Approval process is the same as for any OGC Standard except for documents that originated in an Authoritative Standards Development Organization (Authoritative SDO) or are joint Standards activities between OGC and the Authoritative SDO. The remainder of this subsection provides details on the approval of [lime line-through]#such documents as# OGC Abstract Specification [lime]#Topics#.

NOTE: [lime]#Abstract Specification Topics may be initiated by a SWG or directly by the TC. When an Abstract Specification Topic is developed directly under the TC, the Topic shall be briefed to the TC and any relevant Working Groups prior to OAB Review in advance of public comment. Any comments received as a result of the briefing(s) shall be considered and accepted by the TCC before the document is presented to the OAB.#

[[authoritative-Standards-development-organization]]
==== Authoritative Standards Development Organization

An Authoritative SDO is an organization which operates on a consensus basis to develop Standards and which has been designated to be an Authoritative SDO by the PC. An Authoritative SDO develops key foundational Standards which provide a basis for conceptual and implementation Standards created by the OGC. These foundational Standards may be approved to be part of the OGC Abstract Specification. A list of Authoritative SDOs shall be maintained by the Standards Program. ISO is already considered to be an Authoritative SDO.

The Authoritative SDO shall be notified if one of its Standards is proposed by the OGC to be a Topic of the Abstract Specification. The Authoritative SDO shall have the opportunity to reject the OGC proposal, in which case the Authoritative SDO Standard may still be used as a normative reference by other OGC Standards, but will not be a part of the OGC Abstract Specification. There is no requirement that the Authoritative SDO provide its Standard to the OGC by any basis other than the normal distribution mechanism for the Authoritative SDO, although provision of the Standard for no fee is preferred.

[[scope-and-content]]
==== Scope and Content

The scope of the Abstract Specification (AS) will include any items that the OGC Technical Committee deems appropriate for achieving interoperability in the geodata and geoprocessing market. The AS may include data models, processing models, or other items necessary to implement the mission of the Technical Committee as defined by the OGC Planning Committee from time to time.

The detail of the Abstract Specification shall be sufficient to provide normative references, including models, and technical guidelines as a foundation for Standards. Each Standard, to the extent possible, will provide unambiguous normative and informative information that allows for implementation of Standards in industry-Standard software.

The level of detail of the AS is at the discretion of the Technical Committee as reflected by the actual content that is approved for inclusion in the document itself. The TC approves the content of the Abstract Specification.

There are two categories of potentially unacceptable Abstract Specification change proposals, including:

* Proposals that directly affect the content of an outstanding OGC Consensus Standards process effort (a decision made by the subgroup responsible for processing the proposed changes); and

* Proposals that affect the content of a completed OGC Standard (these issues should be handled in the revision process because they potentially affect both the Abstract Specification and Implementation Standards).

[[authoritative-sdo-documents-as-ogc-abstract-specifications]]
==== Authoritative SDO Documents as OGC Abstract Specifications
footnote:[Please refer to the ISO-OGC Terms of Reference for details of the working relationship between the OGC and ISO TC 211 - Geomatics. https://portal.ogc.org/files/?artifact_id=69074[_https://portal.ogc.org/files/?artifact_id=69074_].]

A new AS Topic Volume or a revision to an existing AS Topic volume may be proposed by the OGC members for the case in which the document was created in an Authoritative SDO activity or a joint OGC and Authoritative SDO-developed activity. There are the two cases: A document entirely developed in the Authoritative SDO and then recommended by OGC members to be an Abstract Specification and a document jointly developed by the OGC and Authoritative SDO memberships. Each case is now described.

[[authoritative-sdo-Standard-as-an-ogc-abstract-specification-topic-volume]]
===== Authoritative SDO Standard as an OGC Abstract Specification Topic Volume

For this case, the Authoritative SDO Standard in question must be at a published or FDIS (Final Draft International Standard, in the case of ISO) status.

* The Authoritative SDO Standard is presented and discussed in an OGC Working Group.

* The WG Members determine that the Authoritative SDO Standard should be a new OGC AS Topic Volume or should be a revision to an existing OGC AS Topic Volume.

* The WG makes a recommendation that the OGC TC should consider the motion to issue an adoption e-vote for the candidate Abstract Specification.

* The recommendation is presented to the TC for discussion - usually at an OGC face to face TC meeting.

* The TC can approve or not the recommendation to approve the adoption e-vote.

* A minimum three-week review period is required prior to issuance of an adoption e-vote.

* The adoption e-vote is initiated and conducted as per the E-vote policy as defined in <<tc-electronic-voting>>.

NOTE: for this case, the TCC will need to ensure that a copy of the Authoritative SDO Standard is freely available to the OGC Members for review. The document shall then be posted to pending documents and the availability of the document announced to the Membership.

[[joint-ogc-authoritative-sdo-Standard-as-an-ogc-abstract-specification-topic-volume]]
===== Joint OGC-Authoritative SDO Standard as an OGC Abstract Specification Topic Volume

For this case, the OGC and the Authoritative SDO have agreed to have a joint Standards development activity. This decision is captured by approval of the Authoritative SDO (in the case of ISO / TC 211 as an official New Work Item Proposal (NWIP)) and approval of an official OGC SWG Charter. The OGC SWG shall be open to participation by both OGC and the Authoritative SDO members. The work of the SWG shall be under the OGC PnP for all activities related to the development and approval of an OGC Standard. There will also be a parallel Edit Committee or equivalent in the Authoritative SDO to process all of the Authoritative SDO requirements for editing, review, and approval of an Authoritative SDO Standard. The SWG Chair shall have responsibility of communicating and coordinating the joint activity.

[[submissions-ogc-Standard-to-other-sdo]]
=== Submission of an OGC Standard for consideration by another SDO

OGC membership may choose to submit an approved OGC Standard to another SDO for adoption of the Standard by that SDO. A number of OGC Standards have been submitted to ISO / TC 211 and are now also approved as ISO Standards. Such a submission will follow the steps below.

* The body or persons controlling the relationship with the other SDO shall approve the submittal and any documentation required for submission; and

* the TC will vote in a Closing Plenary or by email to approve the submission per the rules for <<voting-during-and-between-tc-meetings>>.

[[appeals-process]]
=== Appeals Process

Appeals by any OGC member must be made before the OGC Architecture Board (OAB). Each appeal or issue will be taken on a case-by-case basis, but rulings made by the OAB with approval of the Planning Committee that affect the process will be reflected in these Policies and Procedures. If the member making the appeal is not satisfied by the decision made at the OAB level, the OGC Board of Directors may be presented with the case for final deliberation.

[[the-Standard-editor]]
=== The Standard Editor

In addition to the formation of a SWG, there is a requirement for an editor or editors who will maintain the content of the candidate Standard based on member input and the decisions of the SWG. One or more members can fill the Editor position. The Editor has the responsibility for managing the actual physical editing and maintenance of the Standard document. The editor is neither the author, nor the owner of the document. By way of guidance, the Editor is responsible for:

* The editorial quality of the document: clear language, well written, self-consistent, and proper format;

* Ensuring that the consensus of the SWG and the TC (approval of a CRP or edit and the language of the edit) is captured in the content of the document;

* Keeping modification of the document on schedule -- knowing the content and history of the document well enough to prevent it from going around in circles, in an endless round of modification; and

* Maintaining a revision notes that document what changes were made and in response to which comments or CRPs. These notes will be used as the basis for creating the revision notes document for a given revision/version of a Standard.

The Editor and the SWG Chair may or may not be the same individual.

[[change-request-proposals-crp-to-an-ogc-document]]
=== Change Request Proposals (CRP) to an OGC document

At any time, any OGC member or non-member can submit a CRP. A CRP allows for the formal documentation of a proposed change to an existing, adopted OGC Standard or abstract specification. The change could be an identified error (see <<corrigendum-errata-changes-to-ogc-Standards-full-Standard>>), an inconsistency, a requested enhancement, or a major proposed enhancement. Completed CRP’s shall be submitted on-line using the CR submission application on the OGC web site. Submitted CRP’s are catalogued and stored on a publicly accessible site.

The CR App URL is: http://ogc.standardstracker.org/

CRP’s are used as the basis for new SWG work items. The SWG will only consider proposed changes and enhancements to an adopted implementation that have been documented using the CRP template.

If a SWG does not exist for a given Standard and there are CRP proposals for that Standard, the TCC shall constitute a new SWG under the P&P outlined in the <<policies-specific-to-a-domain-working-group>>.

[[submission-of-change-request-proposals]]
==== Submission of Change Request Proposals

Once a CRP is completed, it shall be submitted to the OGC by posting to the http://ogc.standardstracker.org/[Public Change Request] page. If a CRP is to be discussed during a face to face SWG meeting, such as during a TC meeting, then change requests should be submitted to the CRP archive by the meeting 3-week rule. All CRPs shall be publicly available.

[[evaluation-of-a-change-request-proposal]]
==== Evaluation of a Change Request Proposal

A CRP is processed by appropriate SWG. The SWG shall discuss the proposed CRP and then vote on how the CRP should be processed:

* Reject the CRP with a written reason;

* Accept the CRP but request additional clarification; or

* Accept the CRP with documentation as submitted.

If a CRP is accepted, the SWG will incorporate the contents of the CRP into the designated Standard, either as a revision or a corrigendum. If the CRP is rejected, then the SWG must write a formal response to the CRP submitter(s) explaining the rationale for rejection and then allow the submitter(s) the opportunity to respond and/or resubmit their CRP with modifications.

The disposition of any CRP will be noted on the pubic CRP web site.

[[completion-of-a-change-request-proposal]]
==== Completion of a Change Request Proposal

When a SWG has processed a CRP, the status of the CRP will be changed on the OGC CRP archive. The status and disposition will be modified based on the SWG decisions. The CRP will remain public and available for future reference. The normal procedure for this process is:

* At the completion of the work of the SWG, the SWG chair shall provide the TCC or his designee a list of completed change proposals; and

* The TCC or his designee shall update the status of those CRs on the OGC website.

[[the-Standard-revision-process-full-Standard]]
=== The Standard Revision Process (Full Standard)

A primary function of a Standards Working Group (SWG) is to edit a candidate Standard based on either a) comments received as part of the OGC Consensus Standards process or b) the contents of one or more official OGC Change Request Proposal(s). If any member feels that a Standard needs to be changed, edited, or enhanced, they must submit a Change Request Proposal.

All voting in a SWG, whether for processing a candidate Standard or for revisions to an existing Standard will follow the rules as defined for <<swg-voting>>.

[[the-revision-process]]
==== The Revision Process

The SWG reviews requests for revisions and corrections to a Standard. Requests for revisions must be in the form of comments received during any public review period, such as for the OGC Consensus Standards process, or in the form of official CRPs. Ad-hoc emails and verbal requests at meetings will not be considered as official CRPs. However, the SWG may vote to discuss issues that have not been submitted as CRPs, and may vote to direct one or more of its members to create official CRPs to document an agreement reached as the result of those discussions.

A major or minor version revision of a Standard follows the process of the Full Standards track with the initial revision approved as a Draft Standard. A Corrigendum to a Standard does not require new evidence of implementation and the Corrigendum is approved at the final stage of a Standard.

[[swg-review-of-change-proposals]]
===== SWG Review of Change Proposals

As part of a revision process, the SWG processes CRPs. Please refer to <<change-request-proposals-crp-to-an-ogc-document>> for additional policies and procedures related to change request proposals. Once a list of change proposals has been compiled and the SWG has discussed the proposed changes, the SWG voting members shall vote on the disposition of each of the proposed changes. The SWG has the right to reject a recommended revision, comment, or correction but must provide a written justification for the rejection.

Based on the outcome of the votes, SWG members then make the revisions and corrections to the target Standard. Comments or CRPs received after the formation of a new SWG may or may not be considered for incorporation. This is at the discretion of the members of the SWG.

[[internal-review-and-public-comment]]
===== Internal Review and Public Comment

When the SWG work items are complete and with the approval of the voting members of the SWG, the new revised Standard may be submitted to the OAB and OGC-NA for a review and subsequent release for the 30-day public comment period.

[lime]#For Standards defining APIs where one or more API elements are proposed for removal in the revision, the API element deprecation process (<<deprecating-api-elements>>) will also need to be followed to completion.#

From this point on, the processing of the revision to the Standard is the same as defined in <<review-of-the-received-comments-all>> and subsequent sections.

[[cut-off-date-for-accepting-new-change-request-proposals]]
==== Cut-off date for accepting new Change Request Proposals

CRPs to approved Standard documents or documents currently in revision can be submitted at any time, and then must be considered by the appropriate SWG. A SWG can set and publicize a cut-off date beyond which it will not consider additional CRPs. CRPs submitted after such a cut-off date must be considered as part of future revision activities.

A cut-off date can be announced to the TC using the following rule: That a cut-off takes effect the end of the next meeting after it has been announced. For example, an announcement at a June meeting would take effect at the next TC meeting, which is usually in September.

[[additional-guidance-and-responsibilities-of-a-swg-during-the-revision-process]]
==== Additional Guidance and Responsibilities of a SWG during the revision process

The SWG shall perform the following tasks.

* Develop a plan and schedule for completion of the new revision of the given Standard. The Plan and Schedule, also known as a Road Map, will be made available to all OGC members as well as the Public.

* Work to ensure that revisions to the Standard are consistent and harmonized with other related OGC Standards.

* Work to ensure that the new revision is – as best as can be accomplished – backwards compatible with the previous revision.

* At completion of revisions to a Standard and before the new version is voted on, provide a “release notes” document that describes all the changes to the Standard. The revised Standard will not be considered for adoption until this document is complete.

* Provide a revision notes document using the Standard revisions template that documents the revisions to the Standard resulting from either public comments or CRPs. The revision notes include lists of deprecated capabilities, changes to capabilities, and new capabilities that are added over time.

* Try to complete their work in a timely manner.

* Endeavor to reflect their perception of the consensus of the TC.

[[the-Standard-revision-process-community-Standard]]
=== The Standard Revision Process (Community Standard)

Revision of a Community Standard is treated [lime line-through]#as# [lime]#similar to# a new Community Standard submission and all processes for approval of a Community Standard from submission of a Work Item to vote for final approval are required. [lime]#The only difference in the process is the TC vote to recommend the Work Item for the revised Community Standard for PC approval can occur at a Plenary or via a two-week e-mail vote, i.e., the vote is not a 45 day electronic vote.#

[[corrigendum-errata-changes-to-ogc-Standards]]
=== Corrigendum (errata) Changes to OGC Standards, [lime]#Best Practices, and Community Practices#

From time to time, members and the public will discover errors in a published and approved OGC Standard, [lime]#Best Practice, or Community Practice#. In such cases, a process is required to document and publish the corrections without [lime line-through]#forming a SWGfootnote:[The members may determine that a SWG should be formed to properly discuss the necessary changes to correct the deficiencies. In this case, the SWG Revision P&P will be followed.]# [lime]#creating a new minor or major revision to a document# or submitting a new Community Standard Work Item and that follows the formal TC review and voting process. Under the corrigendum process, an error (or errors) in a published document discovered after adoption and publication is shown with its correction(s) under a separate sheet (or addendum).

This process operates as follows.

1.  An identified error is documented and submitted to the OGC using the Corrigendum Proposal (CRP) template. The submitter(s) of the Corrigendum notify the TCC.

2.  The TCC or designee evaluates to candidate corrigendum to verify that a specific error is being documented.

3.  The TCC or designee communicates the documented error to the editor/author of the specified [lime line-through]#Standard# [lime]#document#.

4.  The editor/author checks the validity of the error and then communicates this information to the OGC membership for comment using Standard OGC communications. The reason for the TC broadcast is that there may be many implementations of [lime line-through]#the# [lime]#a# Standard for which an error has been documented.

5.  If there is concurrence that the corrigendum documents a valid error, the editor/author writes the corrigendum and submits back to the TCC or his designee.

6.  The Membership votes to release (or not) the error (deficiency) correction as a corrigendum. A Corrigendum vote will ask if there is any objection to unanimous consent. In order to speed the process, these votes will last for only two weeks or occur in a TC Meeting Closing Plenary and there is no IPR review requirement.

7.  The corrigendum is published via OGC communications.

[[backwards-compatibility-full-Standard]]
=== Backwards Compatibility (Full Standard)

In all cases of adopted Standards in a revision process, the members will work to insure the highest level of achievable backwards compatibility to the previous release. In those cases in which backwards compatibility cannot be achieved, the SWG will insure that all inconsistencies are highlighted and documented. These will be incorporated into a Standard Revision Release set of notes that must accompany the new revision. Release notes document all enhancements, changes, and compatibility issues resulting from the revision of the interface Standard. Both the TC and the PC reserve the right to review the issues related to backwards compatibility for a given revision of a Standard. If the backwards compatibility issues are deemed too onerous, the TC and/or the PC may elect to reject the proposed revision.

[[proprietary-rights-copyrights-and-disclosure]]
== Proprietary Rights, Copyrights, and Disclosure

[[proprietary-rights]]
=== Proprietary Rights
footnote:[Please read the OGC IPR Policy documents located at http://www.ogc.org/legal[_www.ogc.org/legal_] for the complete text and description of the OGC IPR policy. If at any time there is confusion or conflict between what is stated in the TC P&P and the OGC IPR Policy, the OGC IPR Policy takes precedent.]

During any meeting of the OGC Technical Committee or any subgroup of the TC, no participant shall disclose proprietary information. footnote:[This section clearly places the onus of protection of proprietary rights on the owner of those rights. No discussion of proprietary technology can take place during a TC or TC subgroup meeting, protecting the participants in the meeting from accidental exposure to proprietary information (and consequent future legal problems with that participant's own intellectual property rights). If a TC member wishes to present information of a proprietary nature to members of the TC, he or she may arrange a meeting of the interested parties totally separate from the TC process and meeting.]

In addition, no information of a secret or proprietary nature shall be made available to the OGC as official documents, and no such documents (or documents marked as such) shall be made OGC official documents or forwarded to the membership.

All proprietary information that may nonetheless be disclosed by any participant during any meeting of the TC or any subgroup of the TC shall be deemed to have been disclosed on a non-confidential basis, without any restrictions on use by anyone (except that no valid copyright or patent right shall be deemed to have been waived by such disclosure).

[[copyrights]]
=== Copyrights

All proposals intended to affect the contents of OGC Standards, once submitted to the TC, (a) convey sufficient royalty free license rights to OGC to permit it to publish, license and sublicense the same freely to all third parties, and to permit OGC and all such third parties to own any derivative works base thereon without financial obligation to the submitter, but (b) do not in any way indicate that the submitter has surrendered or waived any copyright or patent in such proposal.

[[disclosure]]
=== Disclosure

It is the policy of the TC that the all pending proposals and documents shall be restricted to member internal distribution. The exceptions are:

* Change Requests Proposals. All CRPs shall be made public; and

* When an external Standards organization requires access to a members’ only document. The TCC, after due consideration and dialogue with the members, may determine that a given document can be shared with the external Standards organization.

[[tc-planning-committee-representatives]]
== TC Planning Committee Representatives

[[role-and-responsibilities]]
=== Role and Responsibilities

As stated in the Bylaws of the OGC, the OGC TC has the right to seat two representatives on the OGC PC. Up to seven representatives may be available in a “pool” and the TCC will work with the representatives to choose the two to attend a specific PC meeting. This section details the role and responsibilities of these individuals and the process for their election.

The role of a TC Representative to the PC is to bring issues of concern to the general TC membership to the attention of the PC and to keep the TC apprised of the activity of the PC. Responsibilities of the representatives include the following:

* Accept documented issues from TC members and bring these forward at PC meetings;

* Provide a report to the TC of the activities that take place at PC meetings no later than two weeks following a PC meeting;

* Be involved in discussions related to the ongoing work and issues in the TC; and

* Vote.

[[elections]]
=== Elections

The election of these representatives will be held according to the following rules.

* Nominations will be made from the ranks of Voting TC Members (an individual or an individual representing an organization already holding a seat on the PC cannot be nominated).

* There must be at least one nominee for each vacancy.

* The nomination must be accepted by the nominee.

* Each Voting TC Member may vote for one candidate per vacancy to be filled.

* Up to seven representatives may be elected, from which no more than two can attend any PC meeting.

* The representatives will be selected in the order of most votes received to fill the available positions.

[[term-of-office]]
=== Term of Office

The term of office for TC representatives to the PC shall be as recommended by the TC with a maximum term of two years. In the case of resignation, removal, death, or termination of TC Membership of a representative, the rules for election will be invoked to fill the vacancy. Also, the TCC may determine that a given TC representative to the PC is not fulfilling their obligations, such as not attending PC meetings on a regular basis. For example, if the TC representative misses two or more meetings in a row. In such a case, the TCC may ask the TC representative to resign and the rules for election will be invoked to fill the vacancy.

[[temporarily-overriding-specified-procedures]]
== Temporarily Overriding Specified Procedures

The Technical Committee may temporarily override specific procedures set forth in this document by a specific motion to override the normal TC Policies and Procedures. Approval of such an override motion shall require a two-thirds majority vote of non-abstaining Voting TC Members, present at a quorate TC meeting or by electronic TC vote.

[[adoption-of-this-policy-document]]
== Adoption of This Policy Document

In order to be accepted or modified, this document must be ratified by electronic vote per <<tc-electronic-voting>> rules.
